#!/usr/bin/env node
/* GENERATED by tools/build-server.mjs from the sibling .ts source — edit the .ts, not this file. */
"use strict";
/*
 * OIE Web Administrator — standalone NodeJS server.
 *
 * Serves the single-page web administrator, reverse-proxies the engine REST
 * API at /api, and loads web admin plugins. See ../README.md.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const path = __importStar(require("path"));
const fs = __importStar(require("fs"));
const http = __importStar(require("http"));
const https = __importStar(require("https"));
const crypto = __importStar(require("crypto"));
const express_1 = __importDefault(require("express"));
const config_1 = require("./config");
const proxy_1 = require("./proxy");
const oidc_1 = require("./oidc");
const plugin_install_1 = require("./plugin-install");
const plugins = __importStar(require("./plugins"));
const config = (0, config_1.load)();
const app = (0, express_1.default)();
const clientDir = path.join(config.root, 'client');
// Dev mode (npm run dev) serves the shell through Vite for HMR; production
// (npm start) serves the static files as before — zero extra dependencies.
const DEV = process.env.WEBADMIN_DEV === '1';
// Build the listening server: HTTPS when config.tls supplies a readable key+cert
// PEM (a convenience for standalone installs), else plain HTTP. Most deployments
// terminate TLS at a reverse proxy instead. Exits with a clear message on a bad key/cert.
function createServer(handler, tls) {
    if (!tls)
        return http.createServer(handler);
    try {
        return https.createServer({
            key: fs.readFileSync(tls.key),
            cert: fs.readFileSync(tls.cert),
            passphrase: tls.passphrase
        }, handler);
    }
    catch (e) {
        console.error(`[tls] Could not read the TLS key/cert (${e.message}). Check config.tls.key and config.tls.cert.`);
        process.exit(1);
    }
}
app.disable('x-powered-by');
// --- Content-Security-Policy -------------------------------------------------
// Same-origin by default. Monaco is now served locally (/vendor/monaco, see
// below) so it needs no CDN — the only external origin left is Google Fonts
// (fonts.googleapis.com / fonts.gstatic.com), which degrades gracefully to the
// system font fallbacks when unreachable (air-gapped). data: covers the
// attachment viewers' inline images/frames.
//
// script-src carries no 'unsafe-inline'/'unsafe-eval': the shell's ONE inline
// script (the importmap) is authorized by a per-response nonce the shell route
// injects, script validation goes through the engine (core/serialize.js), and
// Monaco's workers are covered by worker-src blob:. Style-src keeps
// 'unsafe-inline' (pervasive inline styles). Dev (Vite HMR) still needs inline
// + eval (the react-refresh preamble, dep optimizer) and a WebSocket.
const cspFor = (nonce) => [
    "default-src 'self'",
    DEV ? "script-src 'self' 'unsafe-inline' 'unsafe-eval'"
        : `script-src 'self' 'nonce-${nonce}'`,
    "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
    "font-src 'self' https://fonts.gstatic.com",
    "img-src 'self' data:",
    "worker-src 'self' blob:",
    `connect-src 'self'${DEV ? ' ws: wss:' : ''}`,
    "frame-src 'self' data:",
    "object-src 'none'",
    "base-uri 'self'",
    "frame-ancestors 'none'"
].join('; ');
app.use((req, res, next) => {
    res.locals.cspNonce = crypto.randomBytes(16).toString('base64');
    res.setHeader('Content-Security-Policy', cspFor(res.locals.cspNonce));
    // Plugin files are served from disk by extension (/plugins/:id/*); nosniff
    // stops a mistyped/omitted Content-Type from being sniffed into something
    // executable. Referrer-Policy keeps internal paths (and any engine URL in a
    // query) out of cross-origin Referer headers.
    res.setHeader('X-Content-Type-Options', 'nosniff');
    res.setHeader('Referrer-Policy', 'same-origin');
    next();
});
// --- /api cache posture ------------------------------------------------------
// Nothing under /api may reach the browser's disk cache: engine responses carry
// channel configs (connector passwords) and message content (PHI), and the
// cache is a plaintext file under the profile that outlives logout on a shared
// workstation. Proxied engine responses get this forced in server/proxy.js
// (forceNoStore — writeHead would override a value set here); this middleware
// covers everything else under /api: the local _webadmin routes below and the
// proxy's engine-unreachable error path.
app.use('/api', (req, res, next) => { res.setHeader('Cache-Control', 'no-store'); next(); });
// --- Web-admin plugin install/uninstall (engine-gated) -----------------------
// Local /api/_webadmin/* routes, registered BEFORE the proxy so they're handled
// here (the engine has no such path) while the /api session cookie still flows.
(0, plugin_install_1.installPluginRoutes)(app, config);
// --- Engine REST API proxy ---------------------------------------------------
app.use('/api', (0, proxy_1.createApiProxy)(config));
// OIDC browser redirects must be mounted before static files / SPA fallback.
app.use('/oidc', (0, oidc_1.createOidcRouter)(config));
// --- Web admin metadata ------------------------------------------------------
app.get('/webadmin/config.json', async (req, res) => {
    // This endpoint is served pre-auth (the login screen fetches it), so it must
    // not disclose internal engine URLs. The client selects an engine by its
    // index (the oie-engine cookie) and the proxy resolves the real URL server
    // side (see server/proxy.js); the browser never needs the URL. Names are
    // already host-derived when unset (buildEngines → engineLabel), so the login
    // dropdown and the connected-engine label read fine from `name` alone.
    res.json({
        engines: await Promise.all(config.engines.map(async (e, index) => {
            const oidc = config.oidc[e.name];
            const engineOidc = oidc ? await (0, oidc_1.engineOidcConfiguration)(config, index) : null;
            return { name: e.name, ...(oidc && engineOidc?.configured ? { sso: { providerLabel: oidc.providerLabel, autoRedirect: oidc.autoRedirect } } : {}) };
        })),
        devMode: !!config.devMode,
        version: require('../package.json').version,
        codeTemplateCompletions: config.codeTemplateCompletions !== false
    });
});
// --- Vendored Monaco editor (self-hosted ESM, for air-gapped installs) --------
// Code editors upgrade to Monaco loaded from this local path instead of a CDN, so
// syntax highlighting/completion work with no internet access. The editor bundle
// + workers are built by tools/build-vendor.mjs into client/vendor/monaco/ (ESM,
// self-contained). Mounted here (before the Vite/static frontend) so /vendor/
// monaco/* resolves in dev and prod alike. If the bundle isn't present, editors
// fall back to the plain textarea. Files are (re)built per install, so revalidate
// rather than cache immutably.
app.use('/vendor/monaco', express_1.default.static(path.join(clientDir, 'vendor', 'monaco'), { maxAge: '1d', dotfiles: 'deny' }));
// --- Plugins -----------------------------------------------------------------
// Registered BEFORE the frontend so /plugins/* and /webadmin/plugins.json take
// precedence over Vite/static (plugins are served from disk, unbundled).
const loaded = plugins.install(app, config);
async function start() {
    if (DEV) {
        // --- Vite dev middleware (HMR) -------------------------------------
        // Vite is ESM-only, so load it dynamically; it only matters in dev.
        const { createServer } = await import('vite');
        const vite = await createServer({
            configFile: path.join(config.root, 'vite.config.ts'),
            root: clientDir,
            server: { middlewareMode: true },
            appType: 'spa' // Vite serves/transforms index.html for unmatched GETs
        });
        // The shell + framework modules (/app.js, /core/*.js, /connectors/*.js,
        // /css/*) are transformed and HMR-served by Vite. Plugin imports of
        // /core/ui.js etc. resolve here too, so there's a single instance.
        app.use(vite.middlewares);
    }
    else {
        // --- Static frontend (production) ----------------------------------
        // Serve the built shell (client/dist: bundled app + hashed assets) first,
        // then the source framework (client/core, client/connectors, …) that the
        // bundle AND runtime plugins import externally via /core/*.js — one shared
        // instance. If no build is present, fall back to serving source directly.
        const distDir = path.join(clientDir, 'dist');
        const built = fs.existsSync(path.join(distDir, 'index.html'));
        const shellDir = built ? distDir : clientDir;
        // Shell route: render index.html with <link rel="modulepreload"> hints for
        // each plugin entry (so the browser fetches plugin code in parallel with
        // the app bundle) and the CSP nonce on the importmap — the shell's one
        // inline script, which script-src authorizes per response.
        const indexHtmlPath = path.join(shellDir, 'index.html');
        const serveShell = (req, res) => {
            let html;
            try {
                html = fs.readFileSync(indexHtmlPath, 'utf8');
            }
            catch {
                return res.status(500).type('text').send('index.html not found — run "npm run build"');
            }
            html = html.replace('<script type="importmap"', `<script type="importmap" nonce="${res.locals.cspNonce}"`);
            const preloads = plugins.preloadLinks(config).join('\n  ');
            if (preloads)
                html = html.replace('</head>', `  ${preloads}\n</head>`);
            res.type('html').send(html);
        };
        // The raw file must never bypass the nonce injection: register the shell
        // route for /index.html ahead of the static mounts, and disable their
        // directory-index serving so `/` reaches the fallback too.
        app.get('/index.html', serveShell);
        // dotfiles:'deny' rejects nested dotfile segments (e.g. a /.git/config or
        // .env that ever landed under a served root) — express.static's default
        // 'ignore' only blocks them as a leaf. Matches the /plugins handler.
        if (built)
            app.use(express_1.default.static(distDir, { dotfiles: 'deny', index: false }));
        app.use(express_1.default.static(clientDir, { dotfiles: 'deny', index: false }));
        // SPA fallback. Express 5 named-wildcard note: `/*splat` does NOT match
        // the bare `/` — the braced `/{*splat}` form does, and `/` must reach
        // the shell now that the static mounts no longer serve a directory index.
        app.get('/{*splat}', serveShell);
        // The unbundled-source fallback below cannot actually boot the app: the shell
        // entry is /main.jsx (browsers refuse a text/jsx module) and app.css imports
        // Tailwind, so both need a build step. Say so plainly — the symptom is an
        // otherwise unexplained blank page stuck on the boot splash.
        if (!built)
            console.warn('  [build] No client/dist found — the app WILL NOT LOAD. Run "npm run build" (or "npm run dev" for the Vite dev server).');
    }
    const server = createServer(app, config.tls);
    const scheme = config.tls ? 'https' : 'http';
    server.listen(config.port, config.host, () => {
        console.log('');
        console.log('  Open Integration Engine — Web Administrator');
        console.log('  --------------------------------------------');
        // 0.0.0.0 / :: are bind-all addresses, not browsable — print the loopback
        // URL you actually open, and note the interface it's bound to.
        const wildcard = config.host === '0.0.0.0' || config.host === '::';
        console.log(`  UI:      ${scheme}://${wildcard ? 'localhost' : config.host}:${config.port}`
            + (wildcard ? `  (bound to ${config.host} — all interfaces)` : '')
            + (config.tls ? '  (TLS)' : '')
            + (DEV ? '  (dev — Vite HMR)' : ''));
        if (config.engines.length > 1) {
            console.log(`  Engines: ${config.engines.map((e) => `${e.name} (${e.url})`).join(', ')}`);
        }
        else {
            console.log(`  Engine:  ${config.engines[0].url} (TLS verify: ${config.engines[0].verifyTls})`);
        }
        if (config.devMode)
            console.log('  devMode: ON — a login-entered engine URL will be proxied (trusted deployments only)');
        console.log(`  Plugins: ${loaded.length} loaded`);
        // Bind-posture warning: on a routable interface without TLS, the proxy
        // strips Secure from the JSESSIONID cookie (server/proxy.js), so the
        // admin session — plus channel configs and message content — crosses the
        // network in cleartext. Fine behind an upstream TLS terminator; a nudge
        // when nothing is protecting it.
        const loopback = config.host === '127.0.0.1' || config.host === '::1' || config.host === 'localhost';
        if (!loopback && !config.tls) {
            console.log('');
            console.log('  WARNING: bound to a non-loopback address without TLS — the engine session');
            console.log('           cookie and channel/message data cross the network in cleartext.');
            console.log('           Terminate TLS upstream, set config.tls, or bind host to 127.0.0.1.');
        }
        console.log('');
    });
}
start().catch((err) => {
    console.error('Failed to start web administrator:', err);
    process.exit(1);
});
