/* GENERATED by tools/build-server.mjs from the sibling .ts source — edit the .ts, not this file. */
"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
const assert = __importStar(require("assert"));
const oidc_1 = require("./oidc");
const config_1 = require("./config");
const secret = 'a sufficiently long test client secret';
const now = Date.now();
const txn = { v: 3, state: 'state', nonce: 'nonce', verifier: 'verifier', engineKey: 'k:production', returnPath: '/dashboard?x=1', created: now };
assert.deepStrictEqual((0, oidc_1.openTransaction)((0, oidc_1.sealTransaction)(txn, secret), secret, now), txn);
const sealed = (0, oidc_1.sealTransaction)(txn, secret).split('.');
sealed[1] = (sealed[1][0] === 'A' ? 'B' : 'A') + sealed[1].slice(1);
assert.throws(() => (0, oidc_1.openTransaction)(sealed.join('.'), secret, now), /invalid/);
assert.throws(() => (0, oidc_1.openTransaction)((0, oidc_1.sealTransaction)({ ...txn, created: now - 700000 }, secret), secret, now), /expired/);
// A v2 seal (engine NAME, no key prefix) must not open under v3 — an in-flight
// sign-in across the upgrade fails closed rather than resolving a stale field.
const v2 = { v: 2, state: 'state', nonce: 'nonce', verifier: 'verifier', engineName: 'Production', returnPath: '/', created: now };
assert.throws(() => (0, oidc_1.openTransaction)((0, oidc_1.sealTransaction)(v2, secret), secret, now), /expired/);
// The cookie names its engine in the clear so the callback needs one lookup;
// the prefix is a hint only — the sealed engineKey is what the router re-checks.
// roundTrip models the read side: cookies() decodeURIComponent's the whole value
// before splitTxnCookie sees it, so the write must be ASCII-safe (see below).
const roundTrip = (value) => (0, oidc_1.splitTxnCookie)(decodeURIComponent(value));
const split = roundTrip((0, oidc_1.txnCookieValue)('k:production', (0, oidc_1.sealTransaction)(txn, secret)));
assert.strictEqual(split.engineKey, 'k:production');
assert.deepStrictEqual((0, oidc_1.openTransaction)(split.sealed, secret, now), txn);
// A tampered prefix normally self-defeats: it selects a different engine's
// secret, so the seal does not open at all.
assert.throws(() => (0, oidc_1.openTransaction)(split.sealed, 'a different engine client secret', now), /invalid/);
// But two engines MAY share a client secret, and keyFor() derives from the
// secret alone — so a k:production seal opens cleanly under a k:staging prefix.
// Only the router's `txn.engineKey !== found.engine.key` re-check rejects that
// swap, which is why it is not redundant with the GCM tag.
const swapped = roundTrip((0, oidc_1.txnCookieValue)('k:staging', (0, oidc_1.sealTransaction)(txn, secret)));
assert.strictEqual(swapped.engineKey, 'k:staging');
assert.strictEqual((0, oidc_1.openTransaction)(swapped.sealed, secret, now).engineKey, 'k:production');
assert.notStrictEqual((0, oidc_1.openTransaction)(swapped.sealed, secret, now).engineKey, swapped.engineKey);
// engineKey() preserves \p{L}, so an accented or CJK engine name yields a
// non-ASCII key. Written raw it would be latin1-mangled back into no engine at
// all (or rejected outright as an invalid header char), so the value is
// percent-encoded on write and survives the decoding read.
for (const key of ['k:producción', 'k:北京-engine']) {
    const value = (0, oidc_1.txnCookieValue)(key, (0, oidc_1.sealTransaction)(txn, secret));
    assert.ok(/^[\x20-\x7e]+$/.test(value), `the cookie value for ${key} must be ASCII-safe`);
    assert.strictEqual(roundTrip(value).engineKey, key);
}
// A pre-upgrade v2 cookie carries no prefix; its first segment is the base64url
// IV, which matches no engine key, so the callback fails closed.
assert.strictEqual(roundTrip((0, oidc_1.sealTransaction)(txn, secret)).engineKey.startsWith('k:'), false);
assert.strictEqual((0, oidc_1.splitTxnCookie)(''), null);
assert.strictEqual((0, oidc_1.splitTxnCookie)('no-separator'), null);
assert.strictEqual((0, oidc_1.validReturnPath)('/channels?x=1'), '/channels?x=1');
for (const bad of ['https://evil.test', '//evil.test', '/\\evil.test', 'javascript:alert(1)'])
    assert.strictEqual((0, oidc_1.validReturnPath)(bad), '/');
// Dot segments collapse on parse, so these clear the leading-"//" guard on the
// way IN and would come back out protocol-relative — res.redirect emits that
// verbatim and the browser resolves it to another origin.
for (const bad of ['/..//evil.test', '/.//evil.test', '/foo/../..//evil.test', '/..//evil.test?x=1',
    '/a/../../..//evil.test', '/..\\/evil.test', '/../\\evil.test', '/..//'])
    assert.strictEqual((0, oidc_1.validReturnPath)(bad), '/');
// Dot segments that normalize to a genuine same-origin path still work.
assert.strictEqual((0, oidc_1.validReturnPath)('/foo/../channels'), '/channels');
// The engine wraps every JSON payload under a single XStream root key.
const wrapped = { 'com.mirth.connect.model.LoginStatus': { status: 'SUCCESS', message: '', updatedUsername: 'jdoe' } };
assert.strictEqual((0, oidc_1.unwrapEngineJson)(wrapped).status, 'SUCCESS');
assert.deepStrictEqual((0, oidc_1.unwrapEngineJson)({ status: 'FAIL', message: 'no' }), { status: 'FAIL', message: 'no' });
assert.strictEqual((0, oidc_1.unwrapEngineJson)('SUCCESS'), 'SUCCESS');
const decodeResult = (value) => JSON.parse(Buffer.from(value, 'base64url').toString('utf8'));
assert.strictEqual(decodeResult((0, oidc_1.encodeResult)({ status: 'FAIL', message: 'x'.repeat(5000) })).message.length, 600);
assert.strictEqual(decodeResult((0, oidc_1.encodeResult)({ status: 'SUCCESS' })).status, 'SUCCESS');
const trusted = new Set(['10.0.0.1']);
assert.strictEqual((0, oidc_1.throttleKey)('10.0.0.1', '203.0.113.5, 198.51.100.7', trusted), '198.51.100.7');
assert.strictEqual((0, oidc_1.throttleKey)('192.0.2.9', '203.0.113.5', trusted), '192.0.2.9');
assert.strictEqual((0, oidc_1.throttleKey)('10.0.0.1', undefined, trusted), '10.0.0.1');
const metadata = { issuer: 'https://issuer.test', authorization_endpoint: 'https://issuer.test/auth', token_endpoint: 'https://issuer.test/token' };
const provider = { clientId: 'client' };
const claims = { iss: metadata.issuer, aud: 'client', nonce: 'n', exp: Math.floor(now / 1000) + 60 };
const token = `e30.${Buffer.from(JSON.stringify(claims)).toString('base64url')}.signature`;
assert.deepStrictEqual((0, oidc_1.validateIdTokenClaims)(token, metadata, provider, 'n', now), claims);
assert.throws(() => (0, oidc_1.validateIdTokenClaims)(token, metadata, provider, 'wrong', now), /validation/);
// The config DOCUMENT stays keyed by the human engine name; the runtime map is
// keyed by the engine's stable key, which is what every lookup arrives holding.
const engines = [{ name: 'Production', key: 'k:production', url: 'https://engine.test', verifyTls: true }];
const providerConfig = { enabled: true, discoveryUrl: 'https://issuer.test/.well-known/openid-configuration', clientId: 'client', clientSecret: secret };
const normalized = (0, config_1.normalizeOidc)({ Production: providerConfig }, engines);
assert.ok(normalized['k:production']);
assert.strictEqual(normalized.Production, undefined);
const engineManaged = (0, config_1.normalizeOidc)({ Production: { enabled: true, clientSecret: secret, providerLabel: 'SSO' } }, engines)['k:production'];
assert.strictEqual(engineManaged.discoveryUrl, undefined);
assert.strictEqual(engineManaged.clientId, undefined);
assert.throws(() => (0, config_1.normalizeOidc)({ '0': providerConfig }, engines), /does not match a configured engine name/);
// An empty document is valid (the shipped example) and yields no providers.
assert.deepStrictEqual((0, config_1.normalizeOidc)({}, engines), {});
console.log('oidc tests passed');
