/* GENERATED by tools/build-server.mjs from the sibling .ts source — edit the .ts, not this file. */
"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.sealTransaction = sealTransaction;
exports.openTransaction = openTransaction;
exports.txnCookieValue = txnCookieValue;
exports.splitTxnCookie = splitTxnCookie;
exports.validReturnPath = validReturnPath;
exports.encodeResult = encodeResult;
exports.unwrapEngineJson = unwrapEngineJson;
exports.validateIdTokenClaims = validateIdTokenClaims;
exports.engineOidcConfiguration = engineOidcConfiguration;
exports.withBudget = withBudget;
exports.openBoundTransaction = openBoundTransaction;
exports.routingCookies = routingCookies;
exports.throttleKey = throttleKey;
exports.createOidcRouter = createOidcRouter;
const crypto = __importStar(require("crypto"));
const express_1 = __importDefault(require("express"));
const config_1 = require("./config");
const proxy_1 = require("./proxy");
const TXN_COOKIE = 'oie-oidc-txn';
const RESULT_COOKIE = 'oie-oidc-result';
const TXN_TTL_MS = 10 * 60 * 1000;
const metadataCache = new Map();
function b64(value) { return Buffer.from(value).toString('base64url'); }
function random(size = 32) { return crypto.randomBytes(size).toString('base64url'); }
function keyFor(secret) {
    return Buffer.from(crypto.hkdfSync('sha256', Buffer.from(secret), Buffer.from('oie-webadmin-oidc'), Buffer.from('transaction-cookie-v1'), 32));
}
function sealTransaction(txn, secret) {
    const iv = crypto.randomBytes(12);
    const cipher = crypto.createCipheriv('aes-256-gcm', keyFor(secret), iv);
    const encrypted = Buffer.concat([cipher.update(JSON.stringify(txn)), cipher.final()]);
    return [b64(iv), b64(encrypted), b64(cipher.getAuthTag())].join('.');
}
function openTransaction(value, secret, now = Date.now()) {
    const parts = String(value || '').split('.');
    if (parts.length !== 3)
        throw new Error('invalid transaction');
    try {
        const decipher = crypto.createDecipheriv('aes-256-gcm', keyFor(secret), Buffer.from(parts[0], 'base64url'));
        decipher.setAuthTag(Buffer.from(parts[2], 'base64url'));
        const txn = JSON.parse(Buffer.concat([decipher.update(Buffer.from(parts[1], 'base64url')), decipher.final()]).toString('utf8'));
        if (txn.v !== 3 || typeof txn.created !== 'number' || txn.created > now + 30000 || now - txn.created > TXN_TTL_MS)
            throw new Error('expired transaction');
        return txn;
    }
    catch (error) {
        if (error.message === 'expired transaction')
            throw error;
        throw new Error('invalid transaction');
    }
}
// The transaction cookie carries its engine key in front of the sealed blob:
// `k:<slug>.<iv>.<ct>.<tag>`. The seal is authenticated with that engine's client
// secret, so the callback cannot decrypt without first knowing WHICH engine — the
// prefix answers that in one lookup instead of trying every configured secret in
// turn. The prefix is only a hint and is never trusted: it selects a candidate
// secret, and the sealed engineKey is re-checked against it after decryption, so
// editing the prefix yields a decryption failure or a mismatch, never a swap.
// engineKey() slugifies every non-alphanumeric to '-', so a key holds no '.'.
// The key is percent-encoded because engineKey() preserves \p{L}: an accented or
// CJK engine name yields a non-ASCII key, which a raw Set-Cookie either mangles
// (headers decode as latin1, so "k:producción" returns as "k:producciÃ³n" and
// resolves to no engine) or refuses outright (ERR_INVALID_CHAR above U+00FF).
// Both readers — cookies() here and parseCookies in proxy.ts — decodeURIComponent.
function txnCookieValue(engineKey, sealed) {
    return `${encodeURIComponent(engineKey)}.${sealed}`;
}
// Takes the ALREADY percent-decoded cookie value (cookies() here and parseCookies
// in proxy.ts decode every cookie), so this is deliberately NOT the inverse of
// txnCookieValue — pairing the two directly yields a still-encoded "k%3A…" that
// matches no engine. Decoding here instead would be worse: cookies() has already
// decoded once, so a second pass would resolve a doubly-encoded key.
function splitTxnCookie(value) {
    const at = String(value ?? '').indexOf('.');
    if (at <= 0)
        return null;
    return { engineKey: String(value).slice(0, at), sealed: String(value).slice(at + 1) };
}
function validReturnPath(value) {
    const path = typeof value === 'string' ? value : '/';
    if (!path.startsWith('/') || path.startsWith('//') || path.startsWith('/\\') || /[\r\n]/.test(path))
        return '/';
    try {
        const parsed = new URL(path, 'https://local.invalid');
        // Re-check the NORMALIZED result, not just the input: a dot-segment
        // collapses on parse, so "/..//evil.test" arrives past the leading-"//"
        // guard and comes back out as "//evil.test" — still same-origin by the
        // check below, but a protocol-relative URL that res.redirect emits
        // verbatim and the browser resolves to https://evil.test. This value is
        // attacker-supplied via /oidc/start?return=, so an open redirect here
        // turns a genuine SSO sign-in into a phishing pivot off a trusted origin.
        // Stated as a whitelist: the two escape shapes are "//host" and "/\host",
        // and rejecting anything that is not "/" followed by a non-separator
        // covers both outright, rather than resting on the URL parser folding
        // backslashes for special schemes — true today, but nothing here asserts it.
        const out = parsed.pathname + parsed.search + parsed.hash;
        const sameOrigin = parsed.origin === 'https://local.invalid';
        return sameOrigin && (out === '/' || /^\/[^/\\]/.test(out)) ? out : '/';
    }
    catch {
        return '/';
    }
}
function cookies(req) {
    const result = {};
    for (const item of String(req.headers.cookie || '').split(';')) {
        const at = item.indexOf('=');
        if (at > 0)
            try {
                result[item.slice(0, at).trim()] = decodeURIComponent(item.slice(at + 1).trim());
            }
            catch { /* ignore */ }
    }
    return result;
}
function secureRequest(req, trusted) {
    return !!req.socket.encrypted
        || ((0, proxy_1.isTrustedPeer)(req.socket.remoteAddress, trusted) && req.headers['x-forwarded-proto'] === 'https');
}
function publicOrigin(req, trusted) {
    const host = String(req.headers.host || '');
    if (!/^[A-Za-z0-9._:[\]-]+(?::\d+)?$/.test(host))
        throw new Error('invalid host header');
    return `${secureRequest(req, trusted) ? 'https' : 'http'}://${host}`;
}
// Bound the human-readable part and never cut the encoding itself: a cookie
// truncated mid-base64 decodes as garbage and the login card would show the
// generic failure instead of the engine's actual message.
//
// When clientPluginClass is set the message is NOT prose — it is the MFA
// plugin's opaque challenge, which the authenticator JSON.parses. A TOTP
// enrolment challenge (mode, challenge, secret, otpauth URI) runs past 600
// characters on nothing exotic: a long issuer plus the email-shaped username an
// IdP hands out. Clipping it yields "Unexpected authentication challenge." with
// no way forward, and an SSO account has no local password to fall back on.
//
// A challenge is therefore never truncated — half a challenge is worth exactly
// as much as none. It is sent whole or not at all, and the only bound is what
// the cookie can carry. No fixed challenge cap: any constant large enough to be
// useful is also large enough to overflow the ceiling once updatedUsername is
// long, which drops the challenge anyway — the failure it was meant to prevent.
const PROSE_MAX = 600;
const COOKIE_MAX = 3500;
function encodeResult(payload) {
    const message = String(payload.message ?? '');
    const challenge = !!payload.clientPluginClass;
    const bounded = { ...payload, message: challenge ? message : message.slice(0, PROSE_MAX) };
    const value = b64(JSON.stringify(bounded));
    if (value.length <= COOKIE_MAX)
        return value;
    // Over the ceiling. For prose, dropping the detail still leaves a usable
    // status. For a challenge there is nothing to salvage, so say so plainly
    // rather than handing the card a plugin class it cannot act on — that would
    // surface as the authenticator's confusing "unexpected challenge" instead.
    return challenge
        ? b64(JSON.stringify({ ...bounded, clientPluginClass: '', message: 'This engine requires a second authentication factor, but its challenge is too large to complete in the browser. Use the desktop Administrator.' }))
        : b64(JSON.stringify({ ...bounded, message: '' }));
}
function setResult(res, payload, secure) {
    res.append('Set-Cookie', `${RESULT_COOKIE}=${encodeResult(payload)}; Path=/; Max-Age=120; SameSite=Lax${secure ? '; Secure' : ''}`);
}
async function discovery(provider) {
    const cached = metadataCache.get(provider.discoveryUrl);
    if (cached && cached.expires > Date.now())
        return cached.value;
    const response = await fetch(provider.discoveryUrl, { headers: { accept: 'application/json' }, signal: AbortSignal.timeout(10000) });
    if (!response.ok)
        throw new Error(`discovery returned ${response.status}`);
    const value = await response.json();
    if (!value.issuer || !value.authorization_endpoint || !value.token_endpoint)
        throw new Error('incomplete discovery document');
    for (const endpoint of [value.authorization_endpoint, value.token_endpoint]) {
        const url = new URL(endpoint);
        if (url.protocol !== 'https:' && url.hostname !== 'localhost' && url.hostname !== '127.0.0.1')
            throw new Error('OIDC endpoints must use HTTPS');
    }
    metadataCache.set(provider.discoveryUrl, { expires: Date.now() + 5 * 60 * 1000, value });
    return value;
}
// The engine's ObjectJSONSerializer wraps every JSON payload under a single
// root key (XStream shape); the SPA's api.js normalizes identically. Reduce a
// wrapped LoginStatus to the status object itself; leave bare shapes alone.
function unwrapEngineJson(parsed) {
    if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) {
        const keys = Object.keys(parsed);
        const inner = keys.length === 1 ? parsed[keys[0]] : null;
        if (inner && typeof inner === 'object' && !Array.isArray(inner))
            return inner;
    }
    return parsed;
}
function jwtClaims(token) {
    const parts = token.split('.');
    if (parts.length !== 3)
        throw new Error('invalid ID token');
    return JSON.parse(Buffer.from(parts[1], 'base64url').toString('utf8'));
}
function validateIdTokenClaims(token, metadata, provider, nonce, now = Date.now()) {
    const claims = jwtClaims(token);
    const audiences = Array.isArray(claims.aud) ? claims.aud : [claims.aud];
    if (claims.iss !== metadata.issuer || !audiences.includes(provider.clientId) || claims.nonce !== nonce)
        throw new Error('ID token claim validation failed');
    if (audiences.length > 1 && claims.azp !== provider.clientId)
        throw new Error('ID token authorized-party validation failed');
    const seconds = Math.floor(now / 1000);
    if (typeof claims.exp !== 'number' || claims.exp < seconds - 60 || (claims.nbf != null && claims.nbf > seconds + 60))
        throw new Error('ID token is expired or not active');
    return claims;
}
const engineConfigCache = new Map();
// Probes currently in flight, keyed like the cache. The cache entry is written
// only when a probe RESOLVES, so the TTL alone does not bound concurrency: every
// request arriving inside the timeout window would miss the cache and open its
// own socket. /webadmin/config.json is pre-auth and unthrottled, and the shell
// awaits it before the auth check, so a black-holed engine would turn N
// concurrent page loads into N simultaneous 5s connections and stall every tab
// — signed-in ones included. Callers inside the window share the one probe.
const engineConfigInFlight = new Map();
function engineOidcConfiguration(config, engineKey) {
    const engine = config.engines.find((candidate) => candidate.key === engineKey);
    if (!engine)
        return Promise.resolve(null);
    const cached = engineConfigCache.get(engine.url);
    if (cached && cached.expires > Date.now())
        return Promise.resolve(cached.value);
    const sharing = engineConfigInFlight.get(engine.url);
    if (sharing)
        return sharing;
    // This probe sits on the pre-auth login screen's path (/webadmin/config.json),
    // so it must answer fast and remember failures: a black-holed engine gets a
    // short timeout and a negative-cache entry instead of a stall per page load.
    const probe = (async () => {
        let value = null;
        try {
            // deadlineMs as well as timeoutMs: timeoutMs is an INACTIVITY timer, so
            // an engine that dribbles a byte every few seconds resets it forever.
            // This probe's whole contract is that it settles — the negative cache
            // and the in-flight entry above are only written when it does — so a
            // never-settling probe would pin every later request to the caller's
            // full budget permanently, with no new probe ever started.
            const response = await (0, proxy_1.engineRequest)(engine, { method: 'GET', path: '/api/extensions/oidcauth/public', headers: { accept: 'application/json', 'x-requested-with': 'OpenIntegrationEngine' }, timeoutMs: 5000, deadlineMs: 6000 });
            if (response.status === 200) {
                let parsed = JSON.parse(response.body.toString('utf8'));
                // Extension servlets that return String are serialized by the engine
                // as {"string": "<the json text>"} (XStream shape) — unwrap first.
                if (parsed && typeof parsed === 'object' && typeof parsed.string === 'string')
                    parsed = JSON.parse(parsed.string);
                value = parsed && parsed.configured != null ? parsed : parsed?.publicConfiguration || parsed;
            }
        }
        catch { /* unreachable or malformed — treated as not configured until the negative TTL lapses */ }
        engineConfigCache.set(engine.url, { expires: Date.now() + (value ? 30000 : 15000), value });
        return value;
    })().finally(() => engineConfigInFlight.delete(engine.url));
    engineConfigInFlight.set(engine.url, probe);
    return probe;
}
// Resolves to `work`'s value, or null once `ms` lapses — whichever lands first.
// The work is NOT cancelled: engineOidcConfiguration's probe keeps running behind
// its shared in-flight entry and still populates the cache, so giving up here
// costs the current response its answer, not the answer itself. That guarantee
// depends on the probe actually settling — see its deadlineMs.
function withBudget(work, ms) {
    let timer;
    const lapsed = new Promise((resolve) => {
        timer = setTimeout(() => resolve(null), ms);
        // Never hold the process open for a deadline nobody is waiting on.
        if (typeof timer.unref === 'function')
            timer.unref();
    });
    return Promise.race([work, lapsed]).finally(() => clearTimeout(timer));
}
// Opens a sealed transaction and confirms it belongs to the engine the cookie's
// cleartext prefix selected, and to this callback.
//
// The engineKey re-check is NOT redundant with the GCM tag. keyFor() derives the
// sealing key from the client secret alone, so two engines configured against one
// IdP app registration — a single Entra/Keycloak client fronting Production and
// Staging — share a secret and therefore a sealing key. A transaction started
// against staging then opens cleanly under a `k:production` prefix, and without
// this comparison the staging-issued code would be exchanged against production
// and mint a production session. Only the sealed key says which engine the user
// actually chose.
function openBoundTransaction(sealed, engine, secret, state, now) {
    const txn = openTransaction(sealed, secret, now);
    if (txn.engineKey !== engine.key || state !== txn.state)
        throw new Error('invalid or expired sign-in transaction');
    return txn;
}
// The routing cookies a completed SSO sign-in must leave behind, matching what
// login.tsx's commitEngineSelection writes for a password sign-in — the two have
// to agree or shell.tsx's loadedEngineKey() disagrees with what the login card
// computes and every sign-in is followed by a spurious hard reload.
//
// The key is percent-encoded because engineKey() preserves \p{L}: a raw non-ASCII
// key is read back latin1-mangled (and 421s), or is rejected outright as an
// invalid header character. Both readers — cookies() here and parseCookies in
// proxy.ts — decode. oie-engine-url is cleared in BOTH branches, as the picker
// does: a stale typed URL beside a named-engine choice re-seeds the login card's
// custom field on the next visit.
function routingCookies(config, engine, secure) {
    const attributes = `Path=/; SameSite=Lax${secure ? '; Secure' : ''}`;
    const cleared = (name) => `${name}=; Path=/; Max-Age=0; SameSite=Lax${secure ? '; Secure' : ''}`;
    // No picker means no remembered choice to record — the proxy already ignores
    // the cookie outright in single-engine mode, so writing one only desynchronizes
    // this tab from what the login card computes ('').
    const routable = config.engines.length > 1 || !!config.devMode;
    return [
        cleared('oie-engine-url'),
        routable ? `oie-engine=${encodeURIComponent(engine.key)}; ${attributes}` : cleared('oie-engine')
    ];
}
// Resolves an engine by its stable key (issue #53). A pre-key numeric index is
// not accepted and not translated: it would be a guess at which entry the caller
// meant, which is exactly what the key migration removed.
async function providerFor(config, raw) {
    const engine = config.engines.find((candidate) => candidate.key === String(raw ?? ''));
    if (!engine)
        return null;
    const web = (0, config_1.oidcForEngine)(config, engine.key);
    if (!web)
        return null;
    const reported = await engineOidcConfiguration(config, engine.key);
    const discoveryUrl = reported?.configured ? reported.discoveryUrl : web.discoveryUrl;
    const clientId = reported?.configured ? reported.clientId : web.clientId;
    return discoveryUrl && clientId ? { engine, provider: { ...web, discoveryUrl, clientId } } : null;
}
// The address the throttle should count: behind the deployment's trusted front
// proxy every browser shares one socket address, so use the client the proxy
// reports (the RIGHTMOST X-Forwarded-For hop — appended by the trusted proxy,
// unforgeable by the client, unlike the client-suppliable leftmost entries).
function throttleKey(remoteAddress, forwardedFor, trusted) {
    if ((0, proxy_1.isTrustedPeer)(remoteAddress, trusted)) {
        const hops = String(forwardedFor || '').split(',').map((hop) => hop.trim()).filter(Boolean);
        if (hops.length)
            return hops[hops.length - 1];
    }
    return String(remoteAddress || 'unknown');
}
function limiter(trusted) {
    const hits = new Map();
    return (req, res, next) => {
        const key = throttleKey(req.socket.remoteAddress, req.headers['x-forwarded-for'], trusted);
        const now = Date.now();
        // Drop buckets whose window has fully passed so one-off addresses
        // don't accumulate forever.
        if (hits.size > 1000)
            for (const [stale, times] of hits) {
                if (now - (times[times.length - 1] || 0) >= 60000)
                    hits.delete(stale);
            }
        const recent = (hits.get(key) || []).filter((time) => now - time < 60000);
        if (recent.length >= 30) {
            res.status(429).send('Too many OIDC requests. Try again shortly.');
            return;
        }
        recent.push(now);
        hits.set(key, recent);
        next();
    };
}
function createOidcRouter(config) {
    const router = express_1.default.Router();
    const trusted = new Set(config.trustedProxies || []);
    router.use(limiter(trusted));
    router.get('/start', async (req, res) => {
        const found = await providerFor(config, req.query.engine);
        if (!found) {
            setResult(res, { status: 'FAIL', message: 'SSO is not configured for this engine.' }, secureRequest(req, trusted));
            return res.redirect('/');
        }
        try {
            const metadata = await discovery(found.provider);
            const origin = publicOrigin(req, trusted);
            const verifier = random(48);
            const txn = { v: 3, state: random(), nonce: random(), verifier, engineKey: found.engine.key,
                returnPath: validReturnPath(req.query.return), created: Date.now() };
            const secure = secureRequest(req, trusted);
            res.append('Set-Cookie', `${TXN_COOKIE}=${txnCookieValue(found.engine.key, sealTransaction(txn, found.provider.clientSecret))}; Path=/oidc; HttpOnly; Max-Age=600; SameSite=Lax${secure ? '; Secure' : ''}`);
            const target = new URL(metadata.authorization_endpoint);
            target.searchParams.set('client_id', found.provider.clientId);
            target.searchParams.set('redirect_uri', `${origin}/oidc/callback`);
            target.searchParams.set('response_type', 'code');
            target.searchParams.set('response_mode', 'query');
            target.searchParams.set('scope', found.provider.scopes.join(' '));
            target.searchParams.set('state', txn.state);
            target.searchParams.set('nonce', txn.nonce);
            target.searchParams.set('code_challenge_method', 'S256');
            target.searchParams.set('code_challenge', crypto.createHash('sha256').update(verifier).digest('base64url'));
            // Allowlisted literal only. The login card sends this on a retry
            // after a rejected attempt: the IdP's own SSO session would
            // otherwise silently re-authenticate the same rejected account,
            // making it impossible to switch users.
            if (req.query.prompt === 'login')
                target.searchParams.set('prompt', 'login');
            return res.redirect(target.toString());
        }
        catch (error) {
            console.error(`[oidc] start failed: ${error.message}`);
            setResult(res, { status: 'FAIL', message: 'SSO is unavailable. Use local sign-in.' }, secureRequest(req, trusted));
            return res.redirect('/');
        }
    });
    router.get('/callback', async (req, res) => {
        const secure = secureRequest(req, trusted);
        res.append('Set-Cookie', `${TXN_COOKIE}=; Path=/oidc; HttpOnly; Max-Age=0; SameSite=Lax${secure ? '; Secure' : ''}`);
        let returnPath = '/';
        try {
            // One lookup: the cookie names its engine key in the clear, and the
            // seal — which only that engine's client secret opens — carries the
            // same key for confirmation. A pre-upgrade v2 cookie has no key
            // prefix, so it lands on an unknown engine here and fails closed.
            const parts = splitTxnCookie(cookies(req)[TXN_COOKIE]);
            const found = parts && await providerFor(config, parts.engineKey);
            if (!found || !parts)
                throw new Error('invalid or expired sign-in transaction');
            const txn = openBoundTransaction(parts.sealed, found.engine, found.provider.clientSecret, req.query.state);
            returnPath = txn.returnPath;
            if (typeof req.query.error === 'string')
                throw new Error('The identity provider declined sign-in.');
            if (typeof req.query.code !== 'string' || !req.query.code)
                throw new Error('The identity provider returned no authorization code.');
            const metadata = await discovery(found.provider);
            const form = new URLSearchParams({ grant_type: 'authorization_code', code: req.query.code,
                redirect_uri: `${publicOrigin(req, trusted)}/oidc/callback`, client_id: found.provider.clientId,
                client_secret: found.provider.clientSecret, code_verifier: txn.verifier });
            const tokenResponse = await fetch(metadata.token_endpoint, { method: 'POST', headers: { 'content-type': 'application/x-www-form-urlencoded', accept: 'application/json' }, body: form, signal: AbortSignal.timeout(15000) });
            const tokens = await tokenResponse.json();
            if (!tokenResponse.ok || typeof tokens.id_token !== 'string')
                throw new Error('OIDC token exchange failed');
            const claims = validateIdTokenClaims(tokens.id_token, metadata, found.provider, txn.nonce);
            const body = Buffer.from(new URLSearchParams({ username: String(claims.preferred_username || claims.email || claims.sub || 'oidc'), password: `oidc:${tokens.id_token}` }).toString());
            const headers = { 'content-type': 'application/x-www-form-urlencoded', accept: 'application/json', 'x-requested-with': 'OpenIntegrationEngine', 'content-length': body.length };
            (0, proxy_1.sanitizeForwardHeaders)(headers, req.socket.remoteAddress, req.headers['x-forwarded-for'], trusted);
            const login = await (0, proxy_1.engineRequest)(found.engine, { method: 'POST', path: '/api/users/_login', headers, body });
            let result;
            try {
                result = unwrapEngineJson(JSON.parse(login.body.toString('utf8')));
            }
            catch {
                result = { status: login.status === 200 ? 'SUCCESS' : 'FAIL' };
            }
            const status = result?.status || result;
            if (!status)
                throw new Error('engine rejected SSO');
            const upstreamCookies = Array.isArray(login.headers['set-cookie']) ? login.headers['set-cookie'] : login.headers['set-cookie'] ? [login.headers['set-cookie']] : [];
            for (const cookie of (0, proxy_1.rewriteSetCookies)(upstreamCookies, secure))
                res.append('Set-Cookie', cookie);
            // Route this session the same way a password sign-in would (see
            // login.tsx commitEngineSelection): the stable key when a picker is in
            // play, and NO cookie in single-engine mode. Writing a cookie there
            // would desynchronize shell.tsx's loadedEngineKey() from what the
            // login card computes ('') and force a spurious hard reload on the
            // next sign-in in this tab.
            for (const cookie of routingCookies(config, found.engine, secure))
                res.append('Set-Cookie', cookie);
            // Local auth answers "Incorrect username or password." — an oidc:-prefixed
            // password can only reach local auth when no OIDC plugin intercepted it.
            const pluginMissing = status === 'FAIL' && /incorrect username or password|invalid (username|user name).*password/i.test(String(result.message || ''));
            const message = result.clientPluginClass ? String(result.message || '')
                : pluginMissing ? 'The engine does not accept SSO. Verify that the OIDC Authentication extension is installed and configured.'
                    : status === 'FAIL' ? 'SSO sign-in was rejected.' : String(result.message || '');
            setResult(res, { status, message, clientPluginClass: result.clientPluginClass || '', updatedUsername: result.updatedUsername || '' }, secure);
            return res.redirect(returnPath);
        }
        catch (error) {
            console.error(`[oidc] callback failed: ${error.message}`);
            setResult(res, { status: 'FAIL', message: error.message.startsWith('The identity provider') ? error.message : 'SSO sign-in failed. Use local sign-in or contact an administrator.' }, secure);
            return res.redirect(returnPath);
        }
    });
    return router;
}
