/* GENERATED by tools/build-server.mjs from the sibling .ts source — edit the .ts, not this file. */
"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
const assert = __importStar(require("assert"));
const oidc_1 = require("./oidc");
const config_1 = require("./config");
const secret = 'a sufficiently long test client secret';
const now = Date.now();
const txn = { v: 2, state: 'state', nonce: 'nonce', verifier: 'verifier', engineName: 'Production', returnPath: '/dashboard?x=1', created: now };
assert.deepStrictEqual((0, oidc_1.openTransaction)((0, oidc_1.sealTransaction)(txn, secret), secret, now), txn);
const sealed = (0, oidc_1.sealTransaction)(txn, secret).split('.');
sealed[1] = (sealed[1][0] === 'A' ? 'B' : 'A') + sealed[1].slice(1);
assert.throws(() => (0, oidc_1.openTransaction)(sealed.join('.'), secret, now), /invalid/);
assert.throws(() => (0, oidc_1.openTransaction)((0, oidc_1.sealTransaction)({ ...txn, created: now - 700000 }, secret), secret, now), /expired/);
assert.strictEqual((0, oidc_1.validReturnPath)('/channels?x=1'), '/channels?x=1');
for (const bad of ['https://evil.test', '//evil.test', '/\\evil.test', 'javascript:alert(1)'])
    assert.strictEqual((0, oidc_1.validReturnPath)(bad), '/');
const metadata = { issuer: 'https://issuer.test', authorization_endpoint: 'https://issuer.test/auth', token_endpoint: 'https://issuer.test/token' };
const provider = { clientId: 'client' };
const claims = { iss: metadata.issuer, aud: 'client', nonce: 'n', exp: Math.floor(now / 1000) + 60 };
const token = `e30.${Buffer.from(JSON.stringify(claims)).toString('base64url')}.signature`;
assert.deepStrictEqual((0, oidc_1.validateIdTokenClaims)(token, metadata, provider, 'n', now), claims);
assert.throws(() => (0, oidc_1.validateIdTokenClaims)(token, metadata, provider, 'wrong', now), /validation/);
const engines = [{ name: 'Production', url: 'https://engine.test', verifyTls: true }];
const providerConfig = { enabled: true, discoveryUrl: 'https://issuer.test/.well-known/openid-configuration', clientId: 'client', clientSecret: secret };
assert.ok((0, config_1.normalizeOidc)({ Production: providerConfig }, engines).Production);
const engineManaged = (0, config_1.normalizeOidc)({ Production: { enabled: true, clientSecret: secret, providerLabel: 'SSO' } }, engines).Production;
assert.strictEqual(engineManaged.discoveryUrl, undefined);
assert.strictEqual(engineManaged.clientId, undefined);
assert.throws(() => (0, config_1.normalizeOidc)({ '0': providerConfig }, engines), /does not match a configured engine name/);
console.log('oidc tests passed');
