/* GENERATED by tools/build-server.mjs from the sibling .ts source — edit the .ts, not this file. */
"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.csrfOk = csrfOk;
exports.hasSession = hasSession;
exports.preUploadGate = preUploadGate;
exports.installPluginRoutes = installPluginRoutes;
/*
 * Web-admin plugin install / uninstall — a thin, engine-gated forward.
 *
 * The extension zip is streamed to the engine's own installer, which enforces the
 * EXTENSIONS_MANAGE permission, installs the extension (its Java half AND its
 * `webadmin/` browser half), and serves that web half itself via /api/webplugins.
 * The web administrator keeps NO local copy — a plugin's UI follows the engine it
 * is installed on. So this module just forwards the request and relays the result;
 * authorization and storage are entirely the engine's.
 *
 * Routes are registered under /api/_webadmin/* — handled locally BEFORE the /api
 * proxy — so the engine session cookie (Path=/api) is carried on the request and
 * forwarded to the engine for the authz decision.
 */
const express_1 = __importDefault(require("express"));
const proxy_1 = require("./proxy");
const MAX_UPLOAD = '16mb'; // express.raw cap (engine zips are a few MB)
// CSRF: require the engine's anti-CSRF header. A cross-site request can't set a
// custom header without a preflight the same-origin policy/engine rejects — the
// same guard the proxy relies on.
function csrfOk(req) { return typeof req.headers['x-requested-with'] === 'string' && req.headers['x-requested-with'].length > 0; }
// Cheap pre-parse gate: reject BEFORE express.raw buffers the upload. The engine
// is still the real authorizer (EXTENSIONS_MANAGE), but there is no reason to
// read up to MAX_UPLOAD from a caller that omits the CSRF header or carries no
// engine session cookie — it could never be authorized. Blunts unauthenticated
// memory-pressure/DoS against the web tier.
function hasSession(req) { return /(?:^|;\s*)JSESSIONID=/.test(req.headers['cookie'] || ''); }
function preUploadGate(req, res, next) {
    if (!csrfOk(req))
        return res.status(403).json({ error: 'CSRF', message: 'Missing X-Requested-With header' });
    if (!hasSession(req))
        return res.status(401).json({ error: 'NO_SESSION', message: 'No engine session' });
    next();
}
function relayEngine(res, engineRes) {
    res.status(engineRes.status);
    const ct = engineRes.headers && engineRes.headers['content-type'];
    if (ct)
        res.set('content-type', ct);
    return res.send(engineRes.body);
}
async function handleInstall(req, res, config) {
    if (!csrfOk(req))
        return res.status(403).json({ error: 'CSRF', message: 'Missing X-Requested-With header' });
    const body = req.body;
    if (!Buffer.isBuffer(body) || body.length === 0)
        return res.status(400).json({ error: 'EMPTY', message: 'No upload received' });
    // Forward the upload to the engine — it enforces EXTENSIONS_MANAGE, installs the
    // extension (Java + its webadmin/ half), and serves the web half via /api/webplugins.
    const engine = (0, proxy_1.resolveEngine)(config, req);
    if (!engine)
        return (0, proxy_1.respondEngineUnknown)(req, res);
    let engineRes;
    try {
        engineRes = await (0, proxy_1.engineRequest)(engine, {
            method: 'POST',
            path: '/api/extensions/_install',
            headers: {
                'content-type': req.headers['content-type'],
                'content-length': String(body.length),
                cookie: (0, proxy_1.forwardCookie)(req.headers['cookie']),
                'x-requested-with': req.headers['x-requested-with']
            },
            body
        });
    }
    catch (e) {
        console.error('[plugin-install] engine forward failed:', e.message);
        return res.status(502).json({ error: 'ENGINE_UNREACHABLE', message: 'Could not reach the Open Integration Engine.' });
    }
    if (engineRes.status < 200 || engineRes.status >= 300)
        return relayEngine(res, engineRes); // incl. 401/403 authz
    // The extension (and any web half) loads after the engine restarts.
    res.json({ engineInstalled: true, restartEngine: true });
}
async function handleUninstall(req, res, config) {
    if (!csrfOk(req))
        return res.status(403).json({ error: 'CSRF', message: 'Missing X-Requested-With header' });
    const enginePath = req.body && typeof req.body.path === 'string' ? req.body.path : null;
    if (!enginePath)
        return res.status(400).json({ error: 'NO_PATH', message: 'Extension path is required' });
    // Engine enforces EXTENSIONS_MANAGE on uninstall too, and owns the web half.
    const engine = (0, proxy_1.resolveEngine)(config, req);
    if (!engine)
        return (0, proxy_1.respondEngineUnknown)(req, res);
    let engineRes;
    try {
        const fwd = Buffer.from(enginePath, 'utf8');
        engineRes = await (0, proxy_1.engineRequest)(engine, {
            method: 'POST',
            path: '/api/extensions/_uninstall',
            headers: {
                'content-type': req.headers['content-type'] || 'application/json',
                'content-length': String(fwd.length),
                cookie: (0, proxy_1.forwardCookie)(req.headers['cookie']),
                'x-requested-with': req.headers['x-requested-with']
            },
            body: fwd
        });
    }
    catch (e) {
        console.error('[plugin-install] engine uninstall forward failed:', e.message);
        return res.status(502).json({ error: 'ENGINE_UNREACHABLE', message: 'Could not reach the Open Integration Engine.' });
    }
    if (engineRes.status < 200 || engineRes.status >= 300)
        return relayEngine(res, engineRes);
    res.json({ engineUninstalled: true, restartEngine: true });
}
// Refuse an unresolvable engine selection BEFORE the body parsers buffer the
// request (same rationale as preUploadGate): resolveEngine reads only headers,
// so there is no reason to read up to MAX_UPLOAD for a request that can only
// ever be answered 421. The handlers re-resolve for the actual forward.
function engineGate(config) {
    return (req, res, next) => {
        if (!(0, proxy_1.resolveEngine)(config, req))
            return (0, proxy_1.respondEngineUnknown)(req, res);
        next();
    };
}
// Mount BEFORE the /api proxy in server/index.js.
function installPluginRoutes(app, config) {
    app.post('/api/_webadmin/plugins/_install', preUploadGate, engineGate(config), express_1.default.raw({ type: () => true, limit: MAX_UPLOAD }), (req, res) => handleInstall(req, res, config));
    app.post('/api/_webadmin/plugins/_uninstall', engineGate(config), express_1.default.json({ limit: '64kb' }), (req, res) => handleUninstall(req, res, config));
}
