/* GENERATED by tools/build-core.mjs from the sibling TypeScript source — edit the .ts/.tsx, not this file. */
import { t as translate } from "../core/i18n.js";
/*
 * TCP Listener (TcpReceiverProperties) / TCP Sender (TcpDispatcherProperties).
 *
 * React port: def.render(host, ctx) -> def.component(ctx) => JSX. Field schemas
 * and defaults reused VERBATIM. The transmission-mode block (a plugin point:
 * Basic built-in + MLLP plugin) is the React <TransmissionModePanel>; the
 * connector test button keeps its imperative DOM node via the form's `append`.
 */
import { React } from './react-platform.js';
import { checkbox } from '@oie/web-ui';
import { ConnectorForm, TransmissionModePanel, connectorTestButton, portsInUseButton, listenerAddressField, asBool, YES_NO, defaultSourceProperties, defaultDestinationProperties, defaultListenerProperties, CHARSETS, requireFields } from './react-forms.js';
function defaultFrameMode() {
    return {
        '@class': 'com.mirth.connect.model.transmission.framemode.FrameModeProperties',
        pluginPointName: 'MLLP',
        startOfMessageBytes: '0B',
        endOfMessageBytes: '1C0D'
    };
}
const tcpListener = {
    defaults(version) {
        return {
            '@class': 'com.mirth.connect.connectors.tcp.TcpReceiverProperties',
            '@version': version,
            pluginProperties: null,
            listenerConnectorProperties: defaultListenerProperties(version, '6661'),
            sourceConnectorProperties: defaultSourceProperties(version, {
                responseVariable: 'Auto-generate (After source transformer)',
                firstResponse: true
            }),
            transmissionModeProperties: defaultFrameMode(),
            serverMode: true,
            remoteAddress: '',
            remotePort: '',
            overrideLocalBinding: false,
            reconnectInterval: '5000',
            receiveTimeout: '0',
            bufferSize: '65536',
            maxConnections: '10',
            keepConnectionOpen: true,
            dataTypeBinary: false,
            charsetEncoding: 'DEFAULT_ENCODING',
            respondOnNewConnection: 0,
            responseAddress: '',
            responsePort: '',
            responseConnectorPluginProperties: null
        };
    },
    component({ properties, onChange }) {
        // Server binds and listens locally; Client connects out to a remote
        // address. Swing's modeServer/modeClientRadioActionPerformed keep all the
        // mode-specific fields visible but toggle their enabled state.
        // asBool, not a strict compare: the engine wire shape can deliver
        // "true"/"false" strings, which a strict !== false read as Server mode
        // while validate() below read them as Client — an unresolvable save.
        const serverMode = (p) => asBool(p.serverMode);
        return (React.createElement("div", { className: "flex flex-col gap-4" },
            React.createElement(ConnectorForm, { properties: properties, onChange: onChange, fields: [
                    { section: translate("Listener Settings") },
                    listenerAddressField('listenerConnectorProperties.host', translate("Local Address")),
                    { key: 'listenerConnectorProperties.port', label: translate("Local Port"), type: 'number', width: '90px', append: () => portsInUseButton() }
                ] }),
            React.createElement(TransmissionModePanel, { properties: properties, onChange: onChange }),
            React.createElement(ConnectorForm, { properties: properties, onChange: onChange, fields: [
                    { section: translate("TCP Listener Settings") },
                    { key: 'serverMode', label: translate("Mode"), type: 'radio', refresh: true, options: [
                            { value: true, label: translate("Server") },
                            { value: false, label: translate("Client") }
                        ] },
                    { key: 'remoteAddress', label: translate("Remote Address"), type: 'text', width: '200px', disabled: serverMode },
                    { key: 'remotePort', label: translate("Remote Port"), type: 'number', width: '90px', disabled: serverMode },
                    { key: 'overrideLocalBinding', label: translate("Override Local Binding"), type: 'radio', options: YES_NO, disabled: serverMode },
                    { key: 'reconnectInterval', label: translate("Reconnect Interval (ms)"), type: 'number', width: '90px', disabled: serverMode },
                    { key: 'maxConnections', label: translate("Max Connections"), type: 'number', width: '90px', disabled: (p) => !asBool(p.serverMode) },
                    { key: 'receiveTimeout', label: translate("Receive Timeout (ms)"), type: 'number', width: '90px', tooltip: translate("0 = never time out") },
                    { key: 'bufferSize', label: translate("Buffer Size (bytes)"), type: 'number', width: '90px' },
                    { key: 'keepConnectionOpen', label: translate("Keep Connection Open"), type: 'radio', options: YES_NO },
                    {
                        key: 'dataTypeBinary', label: translate("Data Type"), type: 'radio', refresh: true,
                        // Binary disables Encoding and forces it back to the default (Swing setSelectedIndex(0)).
                        onSet: (p) => { if (asBool(p.dataTypeBinary))
                            p.charsetEncoding = 'DEFAULT_ENCODING'; },
                        options: [
                            { value: true, label: translate("Binary") },
                            { value: false, label: translate("Text") }
                        ]
                    },
                    { key: 'charsetEncoding', label: translate("Encoding"), type: 'select', options: CHARSETS, width: '160px', disabled: (p) => asBool(p.dataTypeBinary) },
                    {
                        key: 'respondOnNewConnection', label: translate("Respond on New Connection"), type: 'radio', refresh: true,
                        options: [
                            { value: 1, label: translate("Yes") },
                            { value: 0, label: translate("No") },
                            { value: 2, label: translate("Message Recovery") }
                        ]
                    },
                    { key: 'responseAddress', label: translate("Response Address"), type: 'text', width: '200px', disabled: (p) => Number(p.respondOnNewConnection) === 0 },
                    { key: 'responsePort', label: translate("Response Port"), type: 'number', width: '90px', disabled: (p) => Number(p.respondOnNewConnection) === 0 }
                ] })));
    },
    // Shared ListenerSettingsPanel.checkProperties: Local Address + Local Port always
    // required. TcpListener.checkProperties: Remote Address/Port + Reconnect Interval
    // required in Client mode (!serverMode); Receive Timeout, Buffer Size and Max
    // Connections always required; Response Address/Port required unless Respond on
    // New Connection is No (0). Numeric/range checks (e.g. maxConnections > 0) skipped.
    validate(properties) {
        return requireFields(properties, [
            { key: 'listenerConnectorProperties.host', label: translate("Local Address") },
            { key: 'listenerConnectorProperties.port', label: translate("Local Port") },
            { key: 'remoteAddress', label: translate("Remote Address"), when: (p) => !asBool(p.serverMode) },
            { key: 'remotePort', label: translate("Remote Port"), when: (p) => !asBool(p.serverMode) },
            { key: 'reconnectInterval', label: translate("Reconnect Interval (ms)"), when: (p) => !asBool(p.serverMode) },
            { key: 'receiveTimeout', label: translate("Receive Timeout (ms)") },
            { key: 'bufferSize', label: translate("Buffer Size (bytes)") },
            { key: 'maxConnections', label: translate("Max Connections") },
            { key: 'responseAddress', label: translate("Response Address"), when: (p) => Number(p.respondOnNewConnection) !== 0 },
            { key: 'responsePort', label: translate("Response Port"), when: (p) => Number(p.respondOnNewConnection) !== 0 }
        ]);
    }
};
const tcpSender = {
    defaults(version) {
        return {
            '@class': 'com.mirth.connect.connectors.tcp.TcpDispatcherProperties',
            '@version': version,
            pluginProperties: null,
            destinationConnectorProperties: defaultDestinationProperties(version, { validateResponse: true }),
            transmissionModeProperties: defaultFrameMode(),
            serverMode: false,
            remoteAddress: '127.0.0.1',
            remotePort: '6660',
            overrideLocalBinding: false,
            localAddress: '0.0.0.0',
            localPort: '0',
            sendTimeout: '5000',
            bufferSize: '65536',
            maxConnections: '10',
            keepConnectionOpen: false,
            checkRemoteHost: false,
            responseTimeout: '5000',
            ignoreResponse: false,
            queueOnResponseTimeout: true,
            dataTypeBinary: false,
            charsetEncoding: 'DEFAULT_ENCODING',
            template: '${message.encodedData}'
        };
    },
    component({ properties, channel, onChange }) {
        // Server binds and listens locally; Client connects out to a remote host.
        // Swing's modeServer/modeClientRadioActionPerformed keep every field
        // visible but toggle enabled state, then re-apply the override-binding and
        // keep-connection-open sub-gating in Client mode.
        const serverMode = (p) => asBool(p.serverMode);
        const localBindingDisabled = (p) => !asBool(p.serverMode) && !asBool(p.overrideLocalBinding);
        const sendDisabled = (p) => asBool(p.serverMode) || !asBool(p.keepConnectionOpen);
        return (React.createElement("div", null,
            React.createElement(TransmissionModePanel, { properties: properties, onChange: onChange }),
            React.createElement(ConnectorForm, { properties: properties, onChange: onChange, fields: [
                    { section: translate("Connection Settings") },
                    // Swing initLayout adds modeClientRadio then modeServerRadio
                    // (TcpSender.java:654-655), so on-screen order is Client, Server.
                    { key: 'serverMode', label: translate("Mode"), type: 'radio', refresh: true, options: [
                            { value: false, label: translate("Client") },
                            { value: true, label: translate("Server") }
                        ] },
                    {
                        key: 'remoteAddress', label: translate("Remote Address"), type: 'text', width: '200px', disabled: serverMode,
                        // Test Connection greys in Server mode (TcpSender.modeServerRadioActionPerformed).
                        append: (p) => connectorTestButton({ path: '/connectors/tcp/_testConnection', channel, properties, disabled: serverMode(p) })
                    },
                    { key: 'remotePort', label: translate("Remote Port"), type: 'number', width: '90px', disabled: serverMode },
                    { key: 'overrideLocalBinding', label: translate("Override Local Binding"), type: 'radio', options: YES_NO, refresh: true, disabled: serverMode },
                    { key: 'localAddress', label: translate("Local Address"), type: 'text', width: '200px', disabled: localBindingDisabled },
                    // Ports in Use follows the Local Port field: on in Server mode or Client+Override.
                    { key: 'localPort', label: translate("Local Port"), type: 'number', width: '90px', append: (p) => portsInUseButton({ disabled: localBindingDisabled(p) }), disabled: localBindingDisabled },
                    { key: 'maxConnections', label: translate("Max Connections"), type: 'number', width: '90px', disabled: (p) => !asBool(p.serverMode) },
                    { key: 'keepConnectionOpen', label: translate("Keep Connection Open"), type: 'radio', options: YES_NO, refresh: true, disabled: serverMode },
                    { key: 'checkRemoteHost', label: translate("Check Remote Host"), type: 'radio', options: YES_NO, disabled: sendDisabled },
                    { key: 'sendTimeout', label: translate("Send Timeout (ms)"), type: 'number', width: '90px', disabled: sendDisabled },
                    { key: 'bufferSize', label: translate("Buffer Size (bytes)"), type: 'number', width: '90px' },
                    {
                        key: 'responseTimeout', label: translate("Response Timeout (ms)"), type: 'number', width: '90px',
                        // Swing pairs the Ignore Response checkbox inline with Response Timeout;
                        // it gates Queue on Response Timeout below.
                        append: (p, ctx) => checkbox(translate("Ignore Response"), asBool(p.ignoreResponse), {
                            onChange: (e) => { p.ignoreResponse = e.target.checked; ctx.onChange(); }
                        }).el
                    },
                    { key: 'queueOnResponseTimeout', label: translate("Queue on Response Timeout"), type: 'radio', options: YES_NO, disabled: (p) => asBool(p.ignoreResponse) },
                    {
                        key: 'dataTypeBinary', label: translate("Data Type"), type: 'radio', refresh: true,
                        // Binary disables Encoding and forces it back to the default (Swing setSelectedIndex(0)).
                        onSet: (p) => { if (asBool(p.dataTypeBinary))
                            p.charsetEncoding = 'DEFAULT_ENCODING'; },
                        options: [
                            { value: true, label: translate("Binary") },
                            { value: false, label: translate("Text") }
                        ]
                    },
                    { key: 'charsetEncoding', label: translate("Encoding"), type: 'select', options: CHARSETS, width: '160px', disabled: (p) => asBool(p.dataTypeBinary) },
                    { section: translate("Template") },
                    { key: 'template', label: translate("Template"), type: 'code', minHeight: '260px' }
                ] })));
    },
    // Swing TcpSender.checkProperties: Remote Address/Port required in Client mode
    // (!serverMode); Local Address/Port required in Server mode or when Override Local
    // Binding is on; Max Connections required in Server mode; Send Timeout required in
    // Client mode with Keep Connection Open; Buffer Size, Response Timeout and Template
    // always required. Numeric/range checks (e.g. maxConnections > 0) skipped.
    validate(properties) {
        return requireFields(properties, [
            { key: 'remoteAddress', label: translate("Remote Address"), when: (p) => !asBool(p.serverMode) },
            { key: 'remotePort', label: translate("Remote Port"), when: (p) => !asBool(p.serverMode) },
            { key: 'localAddress', label: translate("Local Address"), when: (p) => asBool(p.serverMode) || asBool(p.overrideLocalBinding) },
            { key: 'localPort', label: translate("Local Port"), when: (p) => asBool(p.serverMode) || asBool(p.overrideLocalBinding) },
            { key: 'maxConnections', label: translate("Max Connections"), when: (p) => asBool(p.serverMode) },
            { key: 'sendTimeout', label: translate("Send Timeout (ms)"), when: (p) => !asBool(p.serverMode) && asBool(p.keepConnectionOpen) },
            { key: 'bufferSize', label: translate("Buffer Size (bytes)") },
            { key: 'responseTimeout', label: translate("Response Timeout (ms)") },
            { key: 'template', label: translate("Template") }
        ]);
    }
};
export function register(platform) {
    platform.registerConnectorPanel('TCP Listener', 'SOURCE', tcpListener);
    platform.registerConnectorPanel('TCP Sender', 'DESTINATION', tcpSender);
}
