/* GENERATED by tools/build-core.mjs from the sibling .ts source — edit the .ts, not this file. */
import * as oie from "./oie.js";
const BASE = "/api";
const listeners = { sessionExpired: [] };
let sessionExpiredFired = false;
const cloneJson = (o) => JSON.parse(JSON.stringify(o));
function onSessionExpired(fn) {
  listeners.sessionExpired.push(fn);
  return () => {
    const i = listeners.sessionExpired.indexOf(fn);
    if (i >= 0) listeners.sessionExpired.splice(i, 1);
  };
}
function resetSessionExpired() {
  sessionExpiredFired = false;
}
const GATEWAY_STATUSES = /* @__PURE__ */ new Set([502, 503, 504]);
const connectionListeners = [];
let engineReachable = true;
function onConnectionChange(fn) {
  connectionListeners.push(fn);
  return () => {
    const i = connectionListeners.indexOf(fn);
    if (i >= 0) connectionListeners.splice(i, 1);
  };
}
function isEngineReachable() {
  return engineReachable;
}
function setReachable(next) {
  if (next === engineReachable) return;
  engineReachable = next;
  for (const fn of connectionListeners.slice()) {
    try {
      fn(next);
    } catch {
    }
  }
}
function send(url, init, opts) {
  return fetch(url, init).then(
    (response) => {
      setReachable(!GATEWAY_STATUSES.has(response.status));
      return handle(response, opts);
    },
    (err) => {
      setReachable(false);
      throw err;
    }
  );
}
function headers(contentType) {
  const h = {
    // Prefer JSON, but accept anything — several endpoints (/server/version,
    // /server/id, /server/jvm, ...) produce only text/plain and answer 406
    // to a bare application/json Accept header.
    "Accept": "application/json, text/plain;q=0.9, */*;q=0.8",
    "X-Requested-With": "OpenIntegrationEngine-WebAdmin"
  };
  if (contentType) h["Content-Type"] = contentType;
  return h;
}
class ApiError extends Error {
  status;
  /** The raw response text, when the failing response carried one. */
  body;
  constructor(status2, message, body) {
    super(message);
    this.status = status2;
    this.body = body;
  }
}
function unwrap(parsed) {
  if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
    const keys = Object.keys(parsed);
    if (keys.length === 1) return parsed[keys[0]];
  }
  return parsed;
}
function xmlToObj(node) {
  if (!node.children || node.children.length === 0) {
    const text = node.textContent || "";
    if (text === "true") return true;
    if (text === "false") return false;
    if (/^-?\d+$/.test(text) && text.length < 16) return parseInt(text, 10);
    return text;
  }
  const obj = {};
  for (const child of node.children) {
    const value = xmlToObj(child);
    if (Object.prototype.hasOwnProperty.call(obj, child.tagName)) {
      if (!Array.isArray(obj[child.tagName])) obj[child.tagName] = [obj[child.tagName]];
      obj[child.tagName].push(value);
    } else {
      obj[child.tagName] = value;
    }
  }
  return obj;
}
function parseBody(text) {
  if (!text) return null;
  const trimmed = text.trim();
  if (trimmed[0] === "{" || trimmed[0] === "[") {
    try {
      return unwrap(JSON.parse(trimmed));
    } catch {
    }
  }
  if (trimmed[0] === "<") {
    try {
      const doc = new DOMParser().parseFromString(trimmed, "text/xml");
      if (!doc.querySelector("parsererror")) return xmlToObj(doc.documentElement);
    } catch {
    }
  }
  return trimmed;
}
async function handle(response, { raw = false, noAuthHandler = false } = {}) {
  if (response.status === 401) {
    if (noAuthHandler) {
      const text2 = await response.text().catch(() => "");
      let message = "Unauthorized";
      const parsed = parseBody(text2);
      if (parsed && typeof parsed === "object") message = parsed.message || parsed.error || message;
      throw new ApiError(401, message, text2);
    }
    if (!sessionExpiredFired) {
      sessionExpiredFired = true;
      listeners.sessionExpired.forEach((fn) => fn());
    }
    throw new ApiError(401, "Session expired");
  }
  const text = await response.text();
  if (!response.ok) {
    let message = text || `${response.status} ${response.statusText}`;
    const parsed = parseBody(text);
    if (parsed && typeof parsed === "object") {
      message = parsed.message || parsed.detailedError || parsed.error || message;
    }
    throw new ApiError(response.status, message, text);
  }
  if (raw) return text;
  return parseBody(text);
}
function fmtStartEdit(d) {
  return d.toISOString().replace(/\.\d{3}Z$/, "+0000");
}
function qs(params) {
  if (!params) return "";
  const parts = [];
  for (const [key, value] of Object.entries(params)) {
    if (value === void 0 || value === null || value === "") continue;
    for (const v of Array.isArray(value) ? value : [value]) {
      if (v === void 0 || v === null) continue;
      parts.push(`${encodeURIComponent(key)}=${encodeURIComponent(v)}`);
    }
  }
  return parts.length ? "?" + parts.join("&") : "";
}
const enc = encodeURIComponent;
function get(path, params, opts) {
  return send(BASE + path + qs(params), {
    method: "GET",
    headers: headers(),
    credentials: "same-origin"
  }, opts);
}
function post(path, body, { params, contentType = "application/json", wrapKey, raw, noAuthHandler } = {}) {
  let payload = body;
  if (body !== void 0 && body !== null && typeof body !== "string" && !(body instanceof FormData)) {
    payload = JSON.stringify(wrapKey ? { [wrapKey]: body } : body);
  }
  return send(BASE + path + qs(params), {
    method: "POST",
    headers: body instanceof FormData ? headers() : headers(contentType),
    credentials: "same-origin",
    body: payload ?? null
  }, { raw, noAuthHandler });
}
function put(path, body, { params, contentType = "application/json", wrapKey, raw } = {}) {
  let payload = body;
  if (body !== void 0 && body !== null && typeof body !== "string") {
    payload = JSON.stringify(wrapKey ? { [wrapKey]: body } : body);
  }
  return send(BASE + path + qs(params), {
    method: "PUT",
    headers: headers(contentType),
    credentials: "same-origin",
    body: payload ?? null
  }, { raw });
}
function getXml(path, params) {
  return send(BASE + path + qs(params), {
    method: "GET",
    headers: {
      "Accept": "application/xml",
      "X-Requested-With": "OpenIntegrationEngine-WebAdmin"
    },
    credentials: "same-origin"
  }, { raw: true });
}
function postXml(path, xml, params) {
  return post(path, String(xml), { params, contentType: "application/xml" });
}
function putXml(path, xml, params) {
  return put(path, String(xml), { params, contentType: "application/xml" });
}
function del(path, params) {
  return send(BASE + path + qs(params), {
    method: "DELETE",
    headers: headers(),
    credentials: "same-origin"
  });
}
function asList(value, key) {
  if (value === null || value === void 0 || value === "") return [];
  if (key !== void 0 && value && typeof value === "object" && !Array.isArray(value)) {
    if (value[key] !== void 0) {
      value = value[key];
    } else {
      const keys = Object.keys(value).filter((k) => !k.startsWith("@"));
      if (keys.length === 1) {
        const lastSegment = (keys[0].split(".").pop() ?? "").toLowerCase();
        if (lastSegment === key.toLowerCase() || Array.isArray(value[keys[0]])) {
          value = value[keys[0]];
        }
      }
    }
    if (value === null || value === void 0 || value === "") return [];
  }
  return Array.isArray(value) ? value : [value];
}
const auth = {
  // Idle-timeout logout (Swing parity): a distinct engine operation so the event
  // log records "Logged out due to inactivity" instead of a plain logout.
  inactivityLogout: () => post("/users/_inactivityLogout", "", { noAuthHandler: true }),
  // `loginData`, when present, is the second leg of an extended/MFA login: the
  // engine reads it from the X-Mirth-Login-Data header (UserServletInterface
  // .LOGIN_DATA_HEADER) and delegates to its MFA plugin instead of re-checking
  // the password. Matches Swing's client.login-with-header second leg.
  //
  // The login endpoint conveys its result in the BODY (LoginStatus /
  // ExtendedLoginStatus) and returns HTTP 401 for any not-yet-authenticated
  // result — INCLUDING an MFA challenge and plain bad credentials. So we read and
  // return the parsed body for ANY status; the caller inspects `.status` and
  // `.clientPluginClass`. (Using post()/handle() here would throw on the 401 and
  // discard the challenge — the MFA bug.) Only a network failure rejects.
  async login(username, password, loginData) {
    const form = new URLSearchParams({ username, password });
    const h = headers("application/x-www-form-urlencoded");
    if (loginData != null) h["X-Mirth-Login-Data"] = String(loginData);
    const res = await fetch(BASE + "/users/_login", {
      method: "POST",
      headers: h,
      credentials: "same-origin",
      body: form.toString()
    });
    const text = await res.text().catch(() => "");
    const parsed = parseBody(text);
    if (parsed !== null && parsed !== void 0 && parsed !== "") return parsed;
    throw new ApiError(res.status, text || `${res.status} ${res.statusText}`, text);
  },
  logout: () => post("/users/_logout", null, { noAuthHandler: true }),
  current: () => get("/users/current", void 0, { noAuthHandler: true })
};
const users = {
  list: () => get("/users").then((v) => asList(v, "user")),
  get: (idOrName) => get(`/users/${encodeURIComponent(idOrName)}`),
  create: (user) => post("/users", user, { wrapKey: "user" }),
  update: (userId, user) => put(`/users/${enc(userId)}`, user, { wrapKey: "user" }),
  remove: (userId) => del(`/users/${enc(userId)}`),
  updatePassword: (userId, plainPassword) => put(`/users/${enc(userId)}/password`, plainPassword, { contentType: "text/plain" }),
  checkPassword: (plainPassword) => post("/users/_checkPassword", plainPassword, { contentType: "text/plain" }),
  isLoggedIn: (userId) => get(`/users/${enc(userId)}/loggedIn`),
  getPreferences: (userId) => get(`/users/${enc(userId)}/preferences`),
  // opts may pass { raw: true } to get the untouched text — needed for values
  // that are themselves XML (e.g. backgroundColor's <awt-color>), which parseBody
  // would otherwise turn into an object.
  getPreference: (userId, name, opts) => get(`/users/${enc(userId)}/preferences/${enc(name)}`, void 0, opts),
  setPreferences: (userId, props) => put(`/users/${enc(userId)}/preferences`, props, { wrapKey: "properties" }),
  setPreference: (userId, name, value) => put(`/users/${enc(userId)}/preferences/${enc(name)}`, value, { contentType: "text/plain" }),
  acknowledgeNotification: (userId) => post(`/users/${enc(userId)}/notificationAcknowledged`)
};
const channels = {
  list: (channelIds, pollingOnly) => get("/channels", { channelId: channelIds, pollingOnly }).then((v) => asList(v, "channel")),
  // Transformer templates are base64-wrapped on the wire (engine
  // Base64StringConverter); decode on read and re-encode a clone on write so
  // the in-memory channel keeps plain-text templates. See oie.ts.
  get: (channelId) => get(`/channels/${enc(channelId)}`).then((c) => oie.decodeChannelTemplates(c)),
  create: (channel) => post("/channels", oie.encodeChannelTemplates(cloneJson(channel)), { wrapKey: "channel" }),
  // override=false enables the engine's Swing-parity conflict check: the save is
  // rejected (body "false") when the channel changed after `startEdit` (a Date —
  // when the user opened it for editing). Callers prompt, then retry override=true.
  update: (channelId, channel, override = true, startEdit) => put(`/channels/${enc(channelId)}`, oie.encodeChannelTemplates(cloneJson(channel)), {
    wrapKey: "channel",
    params: { override, startEdit: startEdit instanceof Date ? fmtStartEdit(startEdit) : startEdit }
  }),
  remove: (channelId) => del(`/channels/${enc(channelId)}`),
  idsAndNames: () => get("/channels/idsAndNames"),
  connectorNames: (channelId) => get(`/channels/${enc(channelId)}/connectorNames`),
  metaDataColumns: (channelId) => get(`/channels/${enc(channelId)}/metaDataColumns`).then((v) => asList(v, "metaDataColumn")),
  portsInUse: () => get("/channels/portsInUse").then((v) => asList(v, "channelPortData")),
  setEnabled: (channelId, enabled) => post(`/channels/${enc(channelId)}/enabled/${enabled}`),
  setInitialState: (channelId, state) => post(`/channels/${enc(channelId)}/initialState/${state}`)
};
const channelGroups = {
  list: () => get("/channelgroups").then((v) => asList(v, "channelGroup")),
  bulkUpdate: (groups, removedIds = []) => {
    const form = new FormData();
    form.append("channelGroups", new Blob([JSON.stringify({ set: { channelGroup: groups } })], { type: "application/json" }));
    form.append("removedChannelGroupIds", new Blob([JSON.stringify({ set: { string: removedIds } })], { type: "application/json" }));
    return post("/channelgroups/_bulkUpdate", form, { params: { override: true } });
  }
};
const status = {
  list: (channelIds, filter, includeUndeployed) => get("/channels/statuses", { channelId: channelIds, filter, includeUndeployed }).then((v) => asList(v, "dashboardStatus")),
  initial: (fetchSize = 100, filter) => get("/channels/statuses/initial", { fetchSize, filter }),
  one: (channelId) => get(`/channels/${enc(channelId)}/status`),
  start: (channelId) => post(`/channels/${enc(channelId)}/_start`),
  stop: (channelId) => post(`/channels/${enc(channelId)}/_stop`),
  halt: (channelId) => post(`/channels/${enc(channelId)}/_halt`),
  pause: (channelId) => post(`/channels/${enc(channelId)}/_pause`),
  resume: (channelId) => post(`/channels/${enc(channelId)}/_resume`),
  startConnector: (channelId, metaDataId) => post(`/channels/${enc(channelId)}/connector/${metaDataId}/_start`),
  stopConnector: (channelId, metaDataId) => post(`/channels/${enc(channelId)}/connector/${metaDataId}/_stop`)
};
const statistics = {
  list: (channelIds, includeUndeployed) => get("/channels/statistics", { channelId: channelIds, includeUndeployed }).then((v) => asList(v, "channelStatistics")),
  one: (channelId) => get(`/channels/${enc(channelId)}/statistics`),
  clear: (channelIdsToConnectors, received = true, filtered = true, sent = true, errored = true) => {
    const esc = (s) => String(s).replace(/[&<>]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" })[c]);
    const entries = Object.entries(channelIdsToConnectors).map(([channelId, metaDataIds]) => {
      const ids = Array.isArray(metaDataIds) && metaDataIds.length ? metaDataIds : [null];
      const items = ids.map((m) => m == null ? "<null/>" : `<int>${m}</int>`).join("");
      return `<entry><string>${esc(channelId)}</string><list>${items}</list></entry>`;
    });
    return postXml(
      "/channels/_clearStatistics",
      `<map>${entries.join("")}</map>`,
      { received, filtered, sent, error: errored }
    );
  },
  clearAll: () => post("/channels/_clearAllStatistics")
};
const engine = {
  deploy: (channelId, returnErrors = true) => post(`/channels/${enc(channelId)}/_deploy`, null, { params: { returnErrors } }),
  deployMany: (channelIds, returnErrors = true) => post("/channels/_deploy", { set: { string: channelIds } }, { params: { returnErrors } }),
  undeploy: (channelId, returnErrors = true) => post(`/channels/${enc(channelId)}/_undeploy`, null, { params: { returnErrors } }),
  undeployMany: (channelIds, returnErrors = true) => post("/channels/_undeploy", { set: { string: channelIds } }, { params: { returnErrors } }),
  redeployAll: (returnErrors = true) => post("/channels/_redeployAll", null, { params: { returnErrors } })
};
const messages = {
  search: (channelId, params) => get(`/channels/${enc(channelId)}/messages`, params).then((v) => asList(v, "message")),
  count: (channelId, params) => get(`/channels/${enc(channelId)}/messages/count`, params),
  get: (channelId, messageId) => get(`/channels/${enc(channelId)}/messages/${enc(messageId)}`),
  maxMessageId: (channelId) => get(`/channels/${enc(channelId)}/messages/maxMessageId`),
  attachments: (channelId, messageId) => get(`/channels/${enc(channelId)}/messages/${enc(messageId)}/attachments`).then((v) => asList(v, "attachment")),
  attachment: (channelId, messageId, attachmentId) => get(`/channels/${enc(channelId)}/messages/${enc(messageId)}/attachments/${encodeURIComponent(attachmentId)}`),
  // Reattach a DICOM message's pixel-data attachment(s) and return the full,
  // raw Base64 DICOM (Swing getDICOMMessage). Body is the ConnectorMessage.
  getDicom: (channelId, messageId, connectorMessage) => post(`/channels/${enc(channelId)}/messages/${enc(messageId)}/_getDICOMMessage`, connectorMessage, {
    wrapKey: connectorMessage && connectorMessage["@class"] || "com.mirth.connect.donkey.model.message.ConnectorMessage",
    raw: true,
    noAuthHandler: true
  }),
  processNew: (channelId, rawData, destinationMetaDataIds, sourceMapEntries) => {
    const params = {};
    if (destinationMetaDataIds && destinationMetaDataIds.length) params.destinationMetaDataId = destinationMetaDataIds;
    if (sourceMapEntries && sourceMapEntries.length) params.sourceMapEntry = sourceMapEntries;
    return post(`/channels/${enc(channelId)}/messages`, rawData, { contentType: "text/plain", params });
  },
  reprocess: (channelId, messageId, replace = false, filterDestinations = false, metaDataIds = []) => post(`/channels/${enc(channelId)}/messages/${enc(messageId)}/_reprocess`, null, {
    params: { replace, filterDestinations, metaDataId: metaDataIds }
  }),
  remove: (channelId, messageId) => del(`/channels/${enc(channelId)}/messages/${enc(messageId)}`),
  removeAll: (channelId, restartRunningChannels = false, clearStatistics = true) => del(`/channels/${enc(channelId)}/messages/_removeAll`, { restartRunningChannels, clearStatistics })
};
const events = {
  search: (params) => get("/events", params).then((v) => asList(v, "serverEvent")),
  count: (params) => get("/events/count", params),
  get: (eventId) => get(`/events/${enc(eventId)}`),
  maxEventId: () => get("/events/maxEventId")
};
const alerts = {
  list: () => get("/alerts").then((v) => asList(v, "alertModel")),
  get: (alertId) => get(`/alerts/${enc(alertId)}`),
  statuses: () => get("/alerts/statuses").then((v) => asList(v, "alertStatus")),
  create: (alert) => post("/alerts", alert, { wrapKey: "alertModel" }),
  update: (alertId, alert) => put(`/alerts/${enc(alertId)}`, alert, { wrapKey: "alertModel" }),
  remove: (alertId) => del(`/alerts/${enc(alertId)}`),
  enable: (alertId) => post(`/alerts/${enc(alertId)}/_enable`),
  disable: (alertId) => post(`/alerts/${enc(alertId)}/_disable`),
  info: (alertId) => post(`/alerts/${enc(alertId)}/_getInfo`, null),
  options: () => get("/alerts/options")
};
const server = {
  id: () => get("/server/id", null, { raw: true }),
  version: () => get("/server/version", null, { raw: true }),
  buildDate: () => get("/server/buildDate", null, { raw: true }),
  statusCode: () => get("/server/status"),
  time: () => get("/server/time"),
  timezone: () => get("/server/timezone", null, { raw: true }),
  jvm: () => get("/server/jvm", null, { raw: true }),
  about: () => get("/server/about"),
  charsets: () => get("/server/charsets").then((v) => asList(v, "string")),
  settings: () => get("/server/settings"),
  setSettings: (settings) => put("/server/settings", settings, { wrapKey: "serverSettings" }),
  publicSettings: () => get("/server/publicSettings"),
  updateSettings: () => get("/server/updateSettings"),
  setUpdateSettings: (settings) => put("/server/updateSettings", settings, { wrapKey: "updateSettings" }),
  configuration: (params) => get("/server/configuration", params),
  setConfiguration: (config, deploy = false, overwriteConfigMap = false) => put("/server/configuration", config, { wrapKey: "serverConfiguration", params: { deploy, overwriteConfigMap } }),
  testEmail: (properties) => post("/server/_testEmail", properties, { wrapKey: "properties" }),
  generateGUID: () => post("/server/_generateGUID", null, { raw: true }),
  globalScripts: () => get("/server/globalScripts"),
  setGlobalScripts: (scripts) => put("/server/globalScripts", scripts, { wrapKey: "map" }),
  configurationMap: () => get("/server/configurationMap"),
  setConfigurationMap: (map) => put("/server/configurationMap", map, { wrapKey: "map" }),
  channelTags: () => get("/server/channelTags").then((v) => asList(v, "channelTag")),
  setChannelTags: (tags) => put("/server/channelTags", { channelTag: tags }, { wrapKey: "set" }),
  channelDependencies: () => get("/server/channelDependencies").then((v) => asList(v, "channelDependency")),
  setChannelDependencies: (deps) => put("/server/channelDependencies", { channelDependency: deps }, { wrapKey: "set" }),
  channelMetadata: () => get("/server/channelMetadata"),
  setChannelMetadata: (metadata) => put("/server/channelMetadata", metadata, { wrapKey: "map" }),
  resources: () => get("/server/resources"),
  setResources: (resources) => put("/server/resources", resources, { wrapKey: "list" }),
  reloadResource: (resourceId) => post(`/server/resources/${encodeURIComponent(resourceId)}/_reload`),
  databaseDrivers: () => get("/server/databaseDrivers").then((v) => asList(v, "driverInfo")),
  // List<DriverInfo> serializes as { list: { driverInfo: [...] } } (DriverInfo
  // is @XStreamAlias("driverInfo")). Requires the DATABASE_DRIVERS_EDIT perm.
  setDatabaseDrivers: (drivers) => put("/server/databaseDrivers", { driverInfo: drivers }, { wrapKey: "list" }),
  passwordRequirements: () => get("/server/passwordRequirements"),
  encryption: () => get("/server/encryption"),
  licenseInfo: () => get("/server/licenseInfo"),
  protocolsAndCipherSuites: () => get("/server/protocolsAndCipherSuites"),
  rhinoLanguageVersion: () => get("/server/rhinoLanguageVersion")
};
const system = {
  info: () => get("/system/info"),
  stats: () => get("/system/stats")
};
const codeTemplates = {
  libraries: (includeCodeTemplates = true) => get("/codeTemplateLibraries", { includeCodeTemplates }).then((v) => asList(v, "codeTemplateLibrary")),
  list: () => get("/codeTemplates").then((v) => asList(v, "codeTemplate")),
  get: (id) => get(`/codeTemplates/${enc(id)}`),
  // override=false = engine revision check: rejected (body "false") when the sent
  // revision no longer matches the server's (someone else saved since it was read).
  update: (id, codeTemplate, override = true) => put(`/codeTemplates/${enc(id)}`, codeTemplate, { wrapKey: "codeTemplate", params: { override } }),
  remove: (id) => del(`/codeTemplates/${enc(id)}`),
  updateLibraries: (libraries, override = true) => put("/codeTemplateLibraries", { codeTemplateLibrary: libraries }, { wrapKey: "list", params: { override } })
};
const extensions = {
  connectors: () => get("/extensions/connectors"),
  plugins: () => get("/extensions/plugins"),
  metadata: (name) => get(`/extensions/${encodeURIComponent(name)}`),
  isEnabled: (name) => get(`/extensions/${encodeURIComponent(name)}/enabled`),
  setEnabled: (name, enabled) => post(`/extensions/${encodeURIComponent(name)}/_setEnabled`, null, { params: { enabled } }),
  properties: (name) => get(`/extensions/${encodeURIComponent(name)}/properties`),
  setProperties: (name, properties) => put(`/extensions/${encodeURIComponent(name)}/properties`, properties, { wrapKey: "properties" })
};
const databaseTasks = {
  list: () => get("/databaseTasks"),
  get: (taskId) => get(`/databaseTasks/${encodeURIComponent(taskId)}`),
  run: (taskId) => post(`/databaseTasks/${encodeURIComponent(taskId)}/_run`),
  cancel: (taskId) => post(`/databaseTasks/${encodeURIComponent(taskId)}/_cancel`)
};
const api = {
  get,
  post,
  put,
  del,
  getXml,
  postXml,
  putXml,
  asList,
  parseBody,
  onSessionExpired,
  auth,
  users,
  channels,
  channelGroups,
  status,
  statistics,
  engine,
  messages,
  events,
  alerts,
  server,
  system,
  codeTemplates,
  extensions,
  databaseTasks
};
var api_default = api;
export {
  ApiError,
  alerts,
  asList,
  auth,
  channelGroups,
  channels,
  codeTemplates,
  databaseTasks,
  api_default as default,
  del,
  engine,
  events,
  extensions,
  get,
  getXml,
  isEngineReachable,
  messages,
  onConnectionChange,
  onSessionExpired,
  parseBody,
  post,
  postXml,
  put,
  putXml,
  resetSessionExpired,
  server,
  statistics,
  status,
  system,
  users
};
