/* GENERATED by tools/build-core.mjs from the sibling TypeScript source — edit the .ts/.tsx, not this file. */
import { compareText } from './i18n.js';
const commands = [];
/** Register a palette command. Returns an unregister function. */
export function registerCommand(command) {
    commands.push(command);
    return () => {
        const i = commands.indexOf(command);
        if (i !== -1)
            commands.splice(i, 1);
    };
}
/** All registered commands, in section then order then label. */
export function allCommands() {
    return commands.slice().sort((a, b) => compareText(String(a.section || ''), String(b.section || ''))
        || (a.order ?? 100) - (b.order ?? 100)
        || compareText(String(a.label), String(b.label)));
}
/* ---- matching ---------------------------------------------------------------
 * Subsequence, not substring: "vsc" finds "Validate Script". Scoring favours
 * consecutive hits and word starts, so a tight match on a short name beats a
 * scattered one on a long name. Returns null when the needle doesn't match at
 * all, or { score, hits } where `hits` are the matched character indices — the
 * palette highlights them, so the ranking shows its working.
 */
export function fuzzyMatch(text, needle) {
    if (!needle)
        return { score: 0, hits: [] };
    const haystack = String(text).toLowerCase();
    const want = needle.toLowerCase();
    const hits = [];
    let score = 0;
    let from = 0;
    for (let i = 0; i < want.length; i++) {
        const at = haystack.indexOf(want[i], from);
        if (at === -1)
            return null;
        if (i > 0 && at === hits[hits.length - 1] + 1)
            score -= 6; // consecutive run
        if (at === 0 || /[\s\-_:/.]/.test(haystack[at - 1]))
            score -= 4; // start of a word
        score += at - from; // gaps cost
        hits.push(at);
        from = at + 1;
    }
    return { score, hits };
}
