/* GENERATED by tools/build-core.mjs from the sibling TypeScript source — edit the .ts/.tsx, not this file. */
/* Bind API traffic to the tab's engine/session, including the interval between
   sending a request and receiving its response. Cookies themselves are shared
   across tabs. The proxy checks the same context against the request cookies. */
function context() {
    const cookies = {};
    for (const part of (typeof document === 'undefined' ? '' : document.cookie).split(';')) {
        const i = part.indexOf('=');
        if (i < 0)
            continue;
        const raw = part.slice(i + 1).trim();
        try {
            cookies[part.slice(0, i).trim()] = decodeURIComponent(raw);
        }
        catch {
            cookies[part.slice(0, i).trim()] = raw;
        }
    }
    return encodeURIComponent(JSON.stringify(['oie-engine', 'oie-engine-url', 'oie-login'].map(k => cookies[k] || '')));
}
let expected = context();
// Preserve the initiating tab's identity across the external IdP navigation.
if (typeof location !== 'undefined' && /\/oidc\/callback\/?$/.test(location.pathname)) {
    try {
        expected = sessionStorage.getItem('oie-oidc-context') || expected;
    }
    catch { /* unavailable */ }
}
// Called only by the login card after deliberately selecting an engine.
export function adoptEngineContext() { expected = context(); }
export function beginLogin() {
    const generation = Array.from(crypto.getRandomValues(new Uint8Array(16)), b => b.toString(16).padStart(2, '0')).join('');
    document.cookie = `oie-login=${generation}; path=/; samesite=lax${location.protocol === 'https:' ? '; secure' : ''}`;
    adoptEngineContext();
}
export function engineContext() { return expected; }
function changed() {
    if (typeof window !== 'undefined')
        window.dispatchEvent(new Event('oie-session-changed'));
    throw new Error('The browser session changed. Reload to continue.');
}
const responseContexts = new WeakMap();
// fetch resolves at response headers; callers check again after reading a body.
export function assertEngineResponse(response) {
    if (responseContexts.get(response) !== expected)
        throw new Error('Discarded a response from the previous session.');
    if (expected !== context())
        changed();
}
export async function engineFetch(url, init = {}) {
    const sentContext = expected;
    if (sentContext !== context())
        return changed();
    const headers = new Headers(init.headers);
    headers.set('X-OIE-Context', sentContext);
    const response = await fetch(url, { ...init, headers });
    responseContexts.set(response, sentContext);
    assertEngineResponse(response);
    if (response.status === 409 && (await response.clone().json().catch(() => null))?.error === 'SESSION_CHANGED')
        return changed();
    return response;
}
