/* GENERATED by tools/build-core.mjs from the sibling TypeScript source — edit the .ts/.tsx, not this file. */
/*
 * Enforces the engine's "Administrator Auto Logout Interval" (Settings → Server:
 * administratorAutoLogoutIntervalEnabled / administratorAutoLogoutIntervalField).
 *
 * The engine only PUBLISHES the policy (GET /server/publicSettings); enforcement is
 * per-client against real user input — exactly like the Swing client, whose
 * InactivityListener watches AWT events and logs out after the configured minutes.
 * Here activity is any pointer/key/wheel/touch event, recorded as a timestamp (cheap
 * on high-frequency events), and a 30-second local check fires the logout once the
 * idle window elapses. The check loop makes no network calls, so it can never reset
 * the engine's own session inactivity timeout.
 */
import { get } from './api.js';
const EVENTS = ['pointerdown', 'pointermove', 'keydown', 'wheel', 'touchstart'];
let checkTimer = null;
let retryTimer = null;
let unlisten = null;
let generation = 0;
/**
 * Reads the policy and, when enabled with a positive interval, starts watching.
 * `onIdle` runs once when the idle window elapses. Safe to call again (re-login);
 * An explicitly unsupported endpoint means no policy. Transient failures retry
 * without treating network traffic as user activity or installing stale timers.
 */
export async function startIdleLogout(onIdle) {
    stopIdleLogout();
    const current = generation;
    let lastActivity = Date.now();
    let minutes = 0;
    const check = () => {
        if (current !== generation)
            return;
        if (minutes > 0 && Date.now() - lastActivity >= minutes * 60000) {
            stopIdleLogout();
            onIdle();
        }
    };
    const touch = () => { check(); lastActivity = Date.now(); };
    for (const ev of EVENTS)
        window.addEventListener(ev, touch, { passive: true, capture: true });
    window.addEventListener('focus', check);
    unlisten = () => {
        for (const ev of EVENTS)
            window.removeEventListener(ev, touch, { capture: true });
        window.removeEventListener('focus', check);
    };
    const load = async () => {
        try {
            const pub = await get('/server/publicSettings', {}, { timeoutMs: 10_000 });
            if (current !== generation)
                return;
            const enabled = pub?.administratorAutoLogoutIntervalEnabled;
            if (enabled === false || enabled === 'false') {
                stopIdleLogout();
                return;
            }
            // Older engines may publish other settings without this feature.
            if (pub && enabled === undefined && pub.administratorAutoLogoutIntervalField === undefined) {
                stopIdleLogout();
                return;
            }
            const value = Number(pub?.administratorAutoLogoutIntervalField);
            if ((enabled !== true && enabled !== 'true') || !Number.isInteger(value) || value < 1 || value > 60) {
                throw new Error('Invalid administrator idle policy');
            }
            minutes = value;
            check();
            if (current === generation)
                checkTimer = setInterval(check, 30_000);
        }
        catch (e) {
            if (current !== generation)
                return;
            if (e.status === 404 || e.status === 405) {
                stopIdleLogout();
                return;
            }
            retryTimer = setTimeout(() => { retryTimer = null; void load(); }, 30_000);
        }
    };
    await load();
}
export function stopIdleLogout() {
    generation++;
    if (checkTimer) {
        clearInterval(checkTimer);
        checkTimer = null;
    }
    if (retryTimer) {
        clearTimeout(retryTimer);
        retryTimer = null;
    }
    unlisten?.();
    unlisten = null;
}
// Non-sensitive, tab-local marker: reload must not rehydrate an idle session
// whose remote revocation failed. Only a new successful sign-in clears it.
const LOCK_KEY = 'oie-idle-locked';
export function isIdleLocked() {
    try {
        return sessionStorage.getItem(LOCK_KEY) === 'true';
    }
    catch {
        return false;
    }
}
export function setIdleLocked(locked) {
    try {
        if (locked)
            sessionStorage.setItem(LOCK_KEY, 'true');
        else
            sessionStorage.removeItem(LOCK_KEY);
    }
    catch { /* storage unavailable */ }
}
