/* GENERATED by tools/build-core.mjs from the sibling TypeScript source — edit the .ts/.tsx, not this file. */
/*
 * Import version guard — a faithful port of Swing's Frame.promptObjectMigration
 * (client/src/.../Frame.java) via MigrationUtil. Three branches on the export's
 * version vs the connected server's version:
 *
 *   same    -> import silently
 *   newer   -> BLOCK (alertInformation, title "Information")
 *   older / unknown -> CONFIRM the automatic conversion (title "Select an Option")
 *
 * Parity details that matter:
 *   - Version source is the ROOT element's `version` attribute
 *     (MigrationUtil.getSerializedObjectVersion / XStream VERSION_ATTRIBUTE_NAME).
 *   - Compare normalizes BOTH versions to exactly 3 components
 *     (MigrationUtil.compareVersions(v1, v2, 3)) — so 4.6.0.x == 4.6.0.
 *   - Message strings are verbatim from Frame.promptObjectMigration with the
 *     product name "Open Integration Engine" (BrandingConstants.PRODUCT_NAME).
 *
 * Swing guards channels, channel groups, and server configuration with this — NOT
 * alerts or code templates (their import paths rely on the serializer's forward
 * migration). This client additionally gates ALERT imports (issue #40): the
 * protection against a newer-than-server file failing engine-side with a raw
 * error is worth the one deliberate departure from Swing's coverage.
 */
import * as store from './store.js';
const PRODUCT = 'Open Integration Engine';
// MigrationUtil.compareVersions(v1, v2, 3): pad/truncate both to 3 components.
function compareVersions(v1, v2) {
    const norm = (v) => {
        const parts = String(v).split('.');
        while (parts.length < 3)
            parts.push('0');
        return parts.slice(0, 3).map((n) => parseInt(n, 10) || 0);
    };
    const a = norm(v1);
    const b = norm(v2);
    for (let i = 0; i < 3; i++) {
        if (a[i] < b[i])
            return -1;
        if (a[i] > b[i])
            return 1;
    }
    return 0;
}
/**
 * Verdict for importing an export stamped `exportVersion` (Swing objectName, e.g.
 * "channel", "channel or group", "server configuration"):
 *   { action: 'ok' }
 *   { action: 'block',   message }   — newer than the server
 *   { action: 'confirm', message }   — older/unknown; ask before converting
 */
export function checkImportVersion(exportVersion, objectName = 'file') {
    const server = store.getState('serverVersion');
    if (!server)
        return { action: 'ok' }; // server version unknown: engine stays the authority
    if (exportVersion) {
        const comparison = compareVersions(exportVersion, server);
        if (comparison === 0)
            return { action: 'ok' };
        if (comparison > 0) {
            return {
                action: 'block',
                message: `The ${objectName} being imported originated from ${PRODUCT} version ${exportVersion}.\n`
                    + `You are using ${PRODUCT} version ${server}.\n`
                    + `The ${objectName} cannot be imported, because it originated from a newer version of ${PRODUCT}.`
            };
        }
        // older
        return {
            action: 'confirm',
            message: `The ${objectName} being imported originated from ${PRODUCT} version ${exportVersion}.\n`
                + `You are using ${PRODUCT} version ${server}.\n`
                + `Would you like to automatically convert the ${objectName} to the ${server} format?`
        };
    }
    // unknown version
    return {
        action: 'confirm',
        message: `The ${objectName} being imported is from an older or unknown version of ${PRODUCT}.\n`
            + `You are using ${PRODUCT} version ${server}.\n`
            + `Would you like to automatically convert the ${objectName} to the ${server} format?`
    };
}
/** Verdict from parsed export XML: the ROOT element's version attribute, Swing-style. */
export function checkImportVersionFromDoc(doc, objectName) {
    const version = doc?.documentElement?.getAttribute('version');
    return checkImportVersion(version, objectName);
}
/**
 * Verdict for a `<list>`-shaped export, where the versions to judge are the
 * CHILDREN's.
 *
 * XStream stamps the version attribute on each object it serializes, and the
 * `<list>` the engine wraps them in carries none of its own — verified against a
 * 4.6.0 engine for /channels, /channelgroups, /alerts and /codeTemplateLibraries
 * alike, every one of them `<list>` with `<child version="4.6.0">` inside.
 * Reading the root therefore always saw "unknown", so a same-version export
 * prompted "from an older or unknown version" on every single list import.
 *
 * A file may in principle mix versions (hand-merged from two servers), so this
 * judges the set: a newer child blocks — that is the verdict that must win —
 * otherwise one older/unknown child confirms once for the whole file, which is
 * the single prompt Swing gives per document.
 */
export function checkImportVersionForElements(elements, objectName) {
    return checkImportVersionForValues(Array.from(elements || []).map((el) => el.getAttribute('version')), objectName);
}
/**
 * Same set-judgement for version stamps already in hand — the JSON imports,
 * where XStream-JSON carries the attribute as an '@version' key. A .json file
 * must pass the same gate as its .xml twin, or the extension is a bypass.
 */
export function checkImportVersionForValues(versions, objectName) {
    const verdicts = versions.map((v) => checkImportVersion(v, objectName));
    return verdicts.find(v => v.action === 'block')
        ?? verdicts.find(v => v.action === 'confirm')
        ?? { action: 'ok' };
}
