/* GENERATED by tools/build-core.mjs from the sibling TypeScript source — edit the .ts/.tsx, not this file. */
/** React wraps KeyboardEvent; Safari may finish composition before Enter (229). */
export function isComposing(e) {
    const native = e.nativeEvent ?? e;
    return !!native.isComposing || native.keyCode === 229 || e.keyCode === 229;
}
export function isCommitEnter(e) {
    return e.key === 'Enter' && !isComposing(e);
}
