/* GENERATED by tools/build-core.mjs from the sibling TypeScript source — edit the .ts/.tsx, not this file. */
/*
 * Shared variable-reference lists shown beside code editors: the classic
 * Administrator's "Destination Mappings" velocity tokens (connector templates)
 * and the Rhino scope cheat-sheet for channel scripts (filter/transformer steps,
 * auth scripts). Public lists keep the [label, insertText] shape.
 */
// [label, Velocity token, Rhino expression]. Keep expressions embeddable in
// scripts (e.g. `return <expression>;`), without Swing's `var ... =` wrappers.
const destinationMappings = [
    ['Channel ID', '${channelId}', 'channelId'],
    ['Channel Name', '${channelName}', 'channelName'],
    ['Message ID', '${message.messageId}', 'connectorMessage.getMessageId()'],
    ['Raw Data', '${message.rawData}', 'connectorMessage.getRawData()'],
    ['Transformed Data', '${message.transformedData}', 'connectorMessage.getTransformedData()'],
    ['Encoded Data', '${message.encodedData}', 'connectorMessage.getEncodedData()'],
    ['Message Source', '${message.source}', "$('mirth_source')"],
    ['Message Type', '${message.type}', "$('mirth_type')"],
    ['Message Version', '${message.version}', "$('mirth_version')"],
    ['Date', '${date}', 'new java.util.Date()'],
    ['Formatted Date', "${date.get('yyyy-M-d H.m.s')}", "DateUtil.getCurrentDate('yyyy-M-d H.m.s')"],
    ['Timestamp', '${SYSTIME}', 'java.lang.System.currentTimeMillis()'],
    ['Unique ID', '${UUID}', 'UUIDGenerator.getUUID()'],
    ['Original File Name', '${originalFilename}', "$('originalFilename')"],
    ['Count', '${COUNT}', null],
    ['XML Entity Encoder', '${XmlUtil.encode()}', "XmlUtil.encode('message')"],
    ['XML Pretty Printer', '${XmlUtil.prettyPrint()}', "XmlUtil.prettyPrint('message')"],
    ['Escape JSON String', '${JsonUtil.escape()}', "JsonUtil.escape('message')"],
    ['JSON Pretty Printer', '${JsonUtil.prettyPrint()}', "JsonUtil.prettyPrint('message')"],
    ['CDATA Tag', '<![CDATA[]]>', null],
    ['DICOM Message Raw Data', '${DICOMMESSAGE}', 'DICOMUtil.getDICOMRawData(connectorMessage)']
];
export const DESTINATION_MAPPINGS = destinationMappings.map(([label, token]) => [label, token]);
/** Resolve a mapping against the target's current language; null means template-only. */
export function destinationMappingToken(token, language) {
    if (language !== 'javascript' && language !== 'js' && language !== 'rhino')
        return token;
    const mapping = destinationMappings.find(([, velocity]) => velocity === token);
    return mapping ? mapping[2] : token;
}
/* Rhino script scope — the identifiers available inside filter/transformer steps
   and channel scripts (JavaScript context). */
export const SCRIPT_REFERENCE = [
    ['Incoming Message', 'msg'],
    ['Transformed Message', 'tmp'],
    ['Connector Message', 'connectorMessage'],
    ['Channel ID', 'channelId'],
    ['Channel Name', 'channelName'],
    ['Channel Map', "$c('key')"],
    ['Channel Map (put)', "$c('key', value)"],
    ['Source Map', "$s('key')"],
    ['Global Map', "$g('key')"],
    ['Global Channel Map', "$gc('key')"],
    ['Response Map', "$r('key')"],
    ['Configuration Map', "$cfg('key')"],
    ['Attachments', 'getAttachments()'],
    ['Logger', "logger.info('')"],
    ['Unique ID', 'UUIDGenerator.getUUID()'],
    ['Date Util', "DateUtil.getCurrentDate('yyyyMMddHHmmss')"]
];
