/* GENERATED by tools/build-core.mjs from the sibling TypeScript source — edit the .ts/.tsx, not this file. */
import { t } from './i18n.js';
/*
 * Shared variable-reference lists shown beside code editors: the classic
 * Administrator's "Destination Mappings" velocity tokens (connector templates)
 * and the Rhino scope cheat-sheet for channel scripts (filter/transformer steps,
 * auth scripts). Each entry is [label, insertText].
 */
export const DESTINATION_MAPPINGS = [
    [t("Channel ID"), '${channelId}'],
    [t("Channel Name"), '${channelName}'],
    [t("Message ID"), '${message.messageId}'],
    [t("Raw Data"), '${message.rawData}'],
    [t("Transformed Data"), '${message.transformedData}'],
    [t("Encoded Data"), '${message.encodedData}'],
    [t("Message Source"), '${message.source}'],
    [t("Message Type"), '${message.type}'],
    [t("Message Version"), '${message.version}'],
    [t("Date"), '${date}'],
    [t("Formatted Date"), "${date.get('yyyy-M-d H.m.s')}"],
    [t("Timestamp"), '${SYSTIME}'],
    [t("Unique ID"), '${UUID}'],
    [t("Original File Name"), '${originalFilename}'],
    [t("Count"), '${COUNT}'],
    [t("XML Entity Encoder"), '${XmlUtil.encode()}'],
    [t("XML Pretty Printer"), '${XmlUtil.prettyPrint()}'],
    [t("Escape JSON String"), '${JsonUtil.escape()}'],
    [t("JSON Pretty Printer"), '${JsonUtil.prettyPrint()}'],
    [t("CDATA Tag"), '<![CDATA[]]>'],
    [t("DICOM Message Raw Data"), '${DICOMMESSAGE}']
];
/* Rhino script scope — the identifiers available inside filter/transformer steps
   and channel scripts (JavaScript context). */
export const SCRIPT_REFERENCE = [
    [t("Incoming Message"), 'msg'],
    [t("Transformed Message"), 'tmp'],
    [t("Connector Message"), 'connectorMessage'],
    [t("Channel ID"), 'channelId'],
    [t("Channel Name"), 'channelName'],
    [t("Channel Map"), "$c('key')"],
    [t("Channel Map (put)"), "$c('key', value)"],
    [t("Source Map"), "$s('key')"],
    [t("Global Map"), "$g('key')"],
    [t("Global Channel Map"), "$gc('key')"],
    [t("Response Map"), "$r('key')"],
    [t("Configuration Map"), "$cfg('key')"],
    [t("Attachments"), 'getAttachments()'],
    [t("Logger"), "logger.info('')"],
    [t("Unique ID"), 'UUIDGenerator.getUUID()'],
    [t("Date Util"), "DateUtil.getCurrentDate('yyyyMMddHHmmss')"]
];
