/* GENERATED by tools/build-core.mjs from the sibling TypeScript source — edit the .ts/.tsx, not this file. */
/*
 * Shared variable-reference lists shown beside code editors: the classic
 * Administrator's "Destination Mappings" velocity tokens (connector templates)
 * and the Rhino scope cheat-sheet for channel scripts (filter/transformer steps,
 * auth scripts). Public lists keep the [label, insertText] shape.
 */
// [label, Velocity token, JavaScript transfer text]. Match Swing's
// VariableListHandler / VariableTransferable: entries can be expressions,
// statements, or raw fragments (CDATA), depending on where they are inserted.
const destinationMappings = [
    ['Channel ID', '${channelId}', "$('Channel ID')"],
    ['Channel Name', '${channelName}', "$('Channel Name')"],
    ['Message ID', '${message.messageId}', 'connectorMessage.getMessageId()'],
    ['Raw Data', '${message.rawData}', 'connectorMessage.getRawData()'],
    ['Transformed Data', '${message.transformedData}', 'connectorMessage.getTransformedData()'],
    ['Encoded Data', '${message.encodedData}', 'connectorMessage.getEncodedData()'],
    ['Message Source', '${message.source}', "$('mirth_source')"],
    ['Message Type', '${message.type}', "$('mirth_type')"],
    ['Message Version', '${message.version}', "$('mirth_version')"],
    ['Date', '${date}', "var date = DateUtil.getDate('pattern','date');"],
    ['Formatted Date', "${date.get('yyyy-M-d H.m.s')}", "var dateString = DateUtil.getCurrentDate('yyyy-M-d H.m.s');"],
    ['Timestamp', '${SYSTIME}', "var dateString = DateUtil.getCurrentDate('yyyyMMddHHmmss');"],
    ['Unique ID', '${UUID}', 'var uuid = UUIDGenerator.getUUID();'],
    ['Original File Name', '${originalFilename}', "$('originalFilename')"],
    ['Count', '${COUNT}', null],
    ['XML Entity Encoder', '${XmlUtil.encode()}', "var encodedMessage = XmlUtil.encode('message');"],
    ['XML Pretty Printer', '${XmlUtil.prettyPrint()}', "var prettyPrintedMessage = XmlUtil.prettyPrint('message');"],
    ['Escape JSON String', '${JsonUtil.escape()}', "var escapedJSONString = JsonUtil.escape('message');"],
    ['JSON Pretty Printer', '${JsonUtil.prettyPrint()}', "var prettyPrintedMessage = JsonUtil.prettyPrint('message');"],
    ['CDATA Tag', '<![CDATA[]]>', '<![CDATA[]]>'],
    ['DICOM Message Raw Data', '${DICOMMESSAGE}', 'var rawData = DICOMUtil.getDICOMRawData(connectorMessage);']
];
export const DESTINATION_MAPPINGS = destinationMappings.map(([label, token]) => [label, token]);
const JAVASCRIPT_DESTINATION_MAPPINGS = destinationMappings
    .filter(([, , script]) => script !== null)
    .map(([label, , script]) => [label, script]);
/** Swing's destination list uses the connector's transfer mode, not editor syntax.
 * Source receivers and authentication scripts have separate reference contexts. */
export function destinationMappingsFor(properties) {
    if (!properties || typeof properties !== 'object'
        || !('destinationConnectorProperties' in properties) || !properties.destinationConnectorProperties)
        return [];
    const type = '@class' in properties ? properties['@class'] : undefined;
    const javascript = type === 'com.mirth.connect.connectors.js.JavaScriptDispatcherProperties'
        || (type === 'com.mirth.connect.connectors.jdbc.DatabaseDispatcherProperties'
            && 'useScript' in properties && (properties.useScript === true || properties.useScript === 'true'));
    return javascript ? JAVASCRIPT_DESTINATION_MAPPINGS : DESTINATION_MAPPINGS;
}
/* Rhino script scope — the identifiers available inside filter/transformer steps
   and channel scripts (JavaScript context). */
export const SCRIPT_REFERENCE = [
    ['Incoming Message', 'msg'],
    ['Transformed Message', 'tmp'],
    ['Connector Message', 'connectorMessage'],
    ['Channel ID', 'channelId'],
    ['Channel Name', 'channelName'],
    ['Channel Map', "$c('key')"],
    ['Channel Map (put)', "$c('key', value)"],
    ['Source Map', "$s('key')"],
    ['Global Map', "$g('key')"],
    ['Global Channel Map', "$gc('key')"],
    ['Response Map', "$r('key')"],
    ['Configuration Map', "$cfg('key')"],
    ['Attachments', 'getAttachments()'],
    ['Logger', "logger.info('')"],
    ['Unique ID', 'UUIDGenerator.getUUID()'],
    ['Date Util', "DateUtil.getCurrentDate('yyyyMMddHHmmss')"]
];
