/* GENERATED by tools/build-core.mjs from the sibling TypeScript source — edit the .ts/.tsx, not this file. */
/* Safety checks shared by the message browser and compare overlay. */
import api from '@oie/web-api';
import { strictWireList } from './wire-safety.js';
export async function readMetaDataColumnsStrict(channelId) {
    const raw = await api.get(`/channels/${encodeURIComponent(String(channelId))}/metaDataColumns`);
    const columns = strictWireList(raw, 'metaDataColumn', 'channel metadata column list');
    for (const column of columns) {
        if (!column || typeof column !== 'object' || !String(column.name || '').trim()) {
            throw new Error('the engine returned an unusable channel metadata column list');
        }
    }
    return columns;
}
export function hasPatientIdColumn(columns) {
    return columns.some(column => String(column.name || '').toUpperCase() === 'PATIENT_ID');
}
export function requireFreshMessage(message, expected) {
    if (!message || typeof message !== 'object'
        || String(message.messageId ?? '') !== String(expected.messageId)
        || String(message.channelId ?? '') !== String(expected.channelId)) {
        throw new Error(`the engine did not return message ${expected.messageId}`);
    }
    if (expected.metaDataId !== undefined) {
        const entries = message?.connectorMessages?.entry ?? message?.connectorMessages;
        const connectors = api.asList(entries)
            .map((entry) => entry?.connectorMessage ?? (entry?.metaDataId !== undefined ? entry : null))
            .filter(Boolean);
        if (!connectors.some((connector) => Number(connector.metaDataId) === Number(expected.metaDataId))) {
            throw new Error(`connector ${expected.metaDataId} is no longer part of message ${expected.messageId}`);
        }
    }
    return message;
}
