/* GENERATED by tools/build-core.mjs from the sibling .ts source — edit the .ts, not this file. */
function uuid() {
  if (crypto.randomUUID) return crypto.randomUUID();
  return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, (c) => {
    const r = Math.random() * 16 | 0;
    return (c === "x" ? r : r & 3 | 8).toString(16);
  });
}
function elementsToArray(elements) {
  if (!elements || typeof elements !== "object") return [];
  const out = [];
  for (const [type, value] of Object.entries(elements)) {
    if (type.startsWith("@")) continue;
    for (const item of Array.isArray(value) ? value : [value]) {
      if (item && typeof item === "object") out.push({ __type: type, ...item });
    }
  }
  out.sort((a, b) => Number(a.sequenceNumber ?? 0) - Number(b.sequenceNumber ?? 0));
  return out;
}
function arrayToElements(items) {
  if (!items || !items.length) return null;
  const elements = {};
  items.forEach((item, index) => {
    const { __type, ...rest } = item;
    rest.sequenceNumber = String(index);
    const ordered = {};
    for (const k of Object.keys(rest)) if (k.startsWith("@")) ordered[k] = rest[k];
    for (const k of Object.keys(rest)) if (!k.startsWith("@")) ordered[k] = rest[k];
    (elements[__type] = elements[__type] || []).push(ordered);
  });
  return elements;
}
const CHANNEL_STATES = ["STARTED", "STARTING", "STOPPED", "STOPPING", "PAUSED", "PAUSING", "UNDEPLOYED", "DEPLOYING", "UNDEPLOYING", "SYNCING", "UNKNOWN"];
function statePip(state) {
  switch (state) {
    case "STARTED":
      return "ok";
    case "PAUSED":
      return "warn";
    case "STOPPED":
      return "err";
    case "STARTING":
    case "STOPPING":
    case "PAUSING":
    case "DEPLOYING":
    case "UNDEPLOYING":
    case "SYNCING":
      return "busy";
    default:
      return "";
  }
}
function stateLabel(state) {
  if (!state) return "Unknown";
  return state.charAt(0) + state.slice(1).toLowerCase();
}
const MESSAGE_STATUSES = ["RECEIVED", "FILTERED", "TRANSFORMED", "SENT", "QUEUED", "ERROR", "PENDING"];
function messageStatusTag(status) {
  switch (status) {
    case "SENT":
    case "TRANSFORMED":
      return "accent";
    case "ERROR":
      return "red";
    case "QUEUED":
    case "PENDING":
      return "blue";
    case "FILTERED":
      return "amber";
    default:
      return "";
  }
}
const STEP_TYPES = {
  "com.mirth.connect.plugins.javascriptstep.JavaScriptStep": { label: "JavaScript" },
  "com.mirth.connect.plugins.mapper.MapperStep": { label: "Mapper" },
  "com.mirth.connect.plugins.messagebuilder.MessageBuilderStep": { label: "Message Builder" },
  "com.mirth.connect.plugins.xsltstep.XsltStep": { label: "XSLT Step" },
  "com.mirth.connect.plugins.destinationsetfilter.DestinationSetFilterStep": { label: "Destination Set Filter" },
  "com.mirth.connect.plugins.scriptfilestep.ExternalScriptStep": { label: "External Script" },
  "com.mirth.connect.model.IteratorStep": { label: "Iterator" }
};
const RULE_TYPES = {
  "com.mirth.connect.plugins.javascriptrule.JavaScriptRule": { label: "JavaScript" },
  "com.mirth.connect.plugins.rulebuilder.RuleBuilderRule": { label: "Rule Builder" },
  "com.mirth.connect.plugins.scriptfilerule.ExternalScriptRule": { label: "External Script" },
  "com.mirth.connect.model.IteratorRule": { label: "Iterator" }
};
function elementTypeLabel(type) {
  const known = STEP_TYPES[type] || RULE_TYPES[type];
  if (known) return known.label;
  return type.split(".").pop() ?? type;
}
const DEFAULT_RESOURCE = {
  "@class": "linked-hash-map",
  entry: [{ string: ["Default Resource", "[Default Resource]"] }]
};
function rawDataTypeProperties(version) {
  return {
    "@class": "com.mirth.connect.plugins.datatypes.raw.RawDataTypeProperties",
    "@version": version,
    batchProperties: {
      "@class": "com.mirth.connect.plugins.datatypes.raw.RawBatchProperties",
      "@version": version,
      splitType: "JavaScript",
      batchScript: null
    }
  };
}
function emptyTransformer(version) {
  return {
    "@version": version,
    elements: null,
    inboundDataType: "RAW",
    outboundDataType: "RAW",
    inboundProperties: rawDataTypeProperties(version),
    outboundProperties: rawDataTypeProperties(version)
  };
}
function emptyFilter(version) {
  return { "@version": version, elements: null };
}
function defaultSourceConnector(version) {
  return {
    "@version": version,
    metaDataId: 0,
    name: "sourceConnector",
    properties: {
      "@class": "com.mirth.connect.connectors.vm.VmReceiverProperties",
      "@version": version,
      pluginProperties: null,
      sourceConnectorProperties: {
        "@version": version,
        responseVariable: "None",
        respondAfterProcessing: true,
        processBatch: false,
        firstResponse: false,
        processingThreads: 1,
        resourceIds: DEFAULT_RESOURCE,
        queueBufferSize: 1e3
      }
    },
    transformer: emptyTransformer(version),
    filter: emptyFilter(version),
    transportName: "Channel Reader",
    mode: "SOURCE",
    enabled: true,
    waitForPrevious: true
  };
}
function defaultDestinationConnector(version, metaDataId = 1, name = "Destination 1") {
  return {
    "@version": version,
    metaDataId,
    name,
    properties: {
      "@class": "com.mirth.connect.connectors.vm.VmDispatcherProperties",
      "@version": version,
      pluginProperties: null,
      destinationConnectorProperties: {
        "@version": version,
        queueEnabled: false,
        sendFirst: false,
        retryIntervalMillis: 1e4,
        regenerateTemplate: false,
        retryCount: 0,
        rotate: false,
        includeFilterTransformer: false,
        threadCount: 1,
        threadAssignmentVariable: null,
        validateResponse: false,
        resourceIds: DEFAULT_RESOURCE,
        queueBufferSize: 1e3,
        reattachAttachments: true
      },
      channelId: "none",
      channelTemplate: "${message.encodedData}",
      mapVariables: null
    },
    transformer: emptyTransformer(version),
    responseTransformer: emptyTransformer(version),
    filter: emptyFilter(version),
    transportName: "Channel Writer",
    mode: "DESTINATION",
    enabled: true,
    waitForPrevious: true
  };
}
function newChannel(name, version) {
  return {
    "@version": version,
    id: uuid(),
    nextMetaDataId: 2,
    name: name || "New Channel",
    description: "",
    revision: 0,
    sourceConnector: defaultSourceConnector(version),
    destinationConnectors: { connector: [defaultDestinationConnector(version)] },
    preprocessingScript: "// Modify the message variable below to pre process data\nreturn message;",
    postprocessingScript: '// This script executes once after a message has been processed\n// Responses returned from here will be stored as "Postprocessor" in the response map\nreturn;',
    deployScript: "// This script executes once when the channel is deployed\n// You only have access to the globalMap and globalChannelMap here to persist data\nreturn;",
    undeployScript: "// This script executes once when the channel is undeployed\n// You only have access to the globalMap and globalChannelMap here to persist data\nreturn;",
    properties: {
      "@version": version,
      clearGlobalChannelMap: true,
      messageStorageMode: "DEVELOPMENT",
      encryptData: false,
      encryptAttachments: false,
      encryptCustomMetaData: false,
      removeContentOnCompletion: false,
      removeOnlyFilteredOnCompletion: false,
      removeAttachmentsOnCompletion: false,
      initialState: "STARTED",
      // Engine ChannelProperties default is true (Swing parity) — attachment
      // handlers only actually keep their extracted attachments when this is on.
      storeAttachments: true,
      // Default custom metadata columns, matching the engine's
      // ServerSettings.defaultMetaDataColumns (SOURCE + TYPE).
      metaDataColumns: {
        metaDataColumn: [
          { name: "SOURCE", type: "STRING", mappingName: "mirth_source" },
          { name: "TYPE", type: "STRING", mappingName: "mirth_type" }
        ]
      },
      attachmentProperties: { "@version": version, type: "None", properties: null },
      resourceIds: DEFAULT_RESOURCE
    },
    exportData: {
      metadata: {
        enabled: true,
        pruningSettings: { archiveEnabled: true }
      }
    }
  };
}
function destinationsOf(channel) {
  if (!channel || !channel.destinationConnectors) return [];
  const list = channel.destinationConnectors.connector ?? channel.destinationConnectors;
  return Array.isArray(list) ? list : list ? [list] : [];
}
function setDestinations(channel, destinations) {
  channel.destinationConnectors = { connector: destinations };
}
const TEMPLATE_KEYS = ["inboundTemplate", "outboundTemplate"];
function b64DecodeUtf8(b64) {
  const bin = atob(String(b64).replace(/\s+/g, ""));
  return new TextDecoder().decode(Uint8Array.from(bin, (c) => c.charCodeAt(0)));
}
function b64EncodeUtf8(str) {
  const bytes = new TextEncoder().encode(String(str));
  let bin = "";
  for (let i = 0; i < bytes.length; i++) bin += String.fromCharCode(bytes[i]);
  return btoa(bin);
}
function transformersOf(channel) {
  const ch = channel && typeof channel === "object" ? channel : null;
  const out = [];
  if (ch && ch.sourceConnector && ch.sourceConnector.transformer) {
    out.push(ch.sourceConnector.transformer);
  }
  for (const d of destinationsOf(ch)) {
    if (d && d.transformer) out.push(d.transformer);
    if (d && d.responseTransformer) out.push(d.responseTransformer);
  }
  return out;
}
function decodeChannelTemplates(channel) {
  for (const t of transformersOf(channel)) {
    for (const k of TEMPLATE_KEYS) {
      const v = t[k];
      if (v && typeof v === "object" && String(v["@encoding"] || "").toLowerCase() === "base64") {
        try {
          t[k] = b64DecodeUtf8(v.$ ?? "");
        } catch {
          t[k] = "";
        }
      }
    }
  }
  return channel;
}
function encodeChannelTemplates(channel) {
  for (const t of transformersOf(channel)) {
    for (const k of TEMPLATE_KEYS) {
      const v = t[k];
      if (typeof v === "string" && v !== "") {
        t[k] = { "@encoding": "base64", "$": b64EncodeUtf8(v) };
      }
    }
  }
  return channel;
}
function connectorProblems(connector, label, problems) {
  if (!connector || typeof connector !== "object") {
    problems.push(`${label} is missing`);
    return;
  }
  const c = connector;
  if (!c.transportName) problems.push(`${label} type is not set`);
  const p = c.properties;
  if (!p || typeof p !== "object" || !p["@class"]) {
    problems.push(`${label} has no connector settings (properties are missing)`);
  }
}
function validateChannel(channel) {
  const problems = [];
  if (!channel || typeof channel !== "object") return ["Channel is empty"];
  if (!channel.name || !String(channel.name).trim()) problems.push("Channel name is required");
  connectorProblems(channel.sourceConnector, "Source connector", problems);
  const dests = destinationsOf(channel);
  if (!dests.length) problems.push("At least one destination connector is required");
  dests.forEach((d, i) => connectorProblems(d, d && (d.name || `Destination ${d.metaDataId ?? i + 1}`), problems));
  return problems;
}
export {
  CHANNEL_STATES,
  MESSAGE_STATUSES,
  RULE_TYPES,
  STEP_TYPES,
  arrayToElements,
  decodeChannelTemplates,
  defaultDestinationConnector,
  defaultSourceConnector,
  destinationsOf,
  elementTypeLabel,
  elementsToArray,
  emptyFilter,
  emptyTransformer,
  encodeChannelTemplates,
  messageStatusTag,
  newChannel,
  setDestinations,
  stateLabel,
  statePip,
  uuid,
  validateChannel
};
