/* GENERATED by tools/build-core.mjs from the sibling .ts source — edit the .ts, not this file. */
export function passwordRequirementHints(req) {
    const r = (req && (req.passwordRequirements || req)) || {};
    const num = (k) => { const v = Number(r[k]); return Number.isFinite(v) ? v : 0; };
    const hints = [];
    const minLength = num('minLength');
    if (minLength > 0)
        hints.push(`at least ${minLength} character${minLength === 1 ? '' : 's'}`);
    const rule = (key, noun) => {
        const v = num(key);
        if (v === -1)
            hints.push(`no ${noun}s`);
        else if (v === 1)
            hints.push(`1 ${noun}`);
        else if (v > 1)
            hints.push(`${v} ${noun}s`);
    };
    rule('minUpper', 'uppercase letter');
    rule('minLower', 'lowercase letter');
    rule('minNumeric', 'number');
    rule('minSpecial', 'special character');
    return hints;
}
