/* GENERATED by tools/build-core.mjs from the sibling TypeScript source — edit the .ts/.tsx, not this file. */
/* @oie/web-shell public surface — the platform extension points + loadPlugins.
   Served barrel (import-map + Vite-alias target). The published package's type
   declarations are emitted from this graph (tsconfig.types-shell.json ->
   gen:types), so what compiles here IS the plugin-author contract. */
export { platform, loadPlugins, OIE_API_VERSION, apiCompatible } from './platform.js';
