/* GENERATED by tools/build-core.mjs from the sibling TypeScript source — edit the .ts/.tsx, not this file. */
/* @oie/web-ui public surface — DOM toolkit, columns, code-editor factory, and
   the connector-panel toolkit (form builder, poll/connector helpers, default
   property shapes). Served barrel (import-map + Vite-alias target). The
   published package's type declarations are emitted from this graph
   (tsconfig.types-ui.json -> gen:types), so what compiles here IS the
   plugin-author contract.

   The connector helpers live here because they're UI building blocks for
   *property panels*: a connector like SQS is an engine extension; its web admin
   half is only a settings panel built with these. */
export * from './ui.js';
export * from './columns.js';
export * from './codeeditor.js';
export * from './mappings.js';
// react-forms re-exports the pure ./forms.js helpers AND adds the React form
// components (ConnectorForm, PollSection, …) that React connector plugins use.
export * from '../connectors/react-forms.js';
