/* GENERATED by tools/build-core.mjs from the sibling TypeScript source — edit the .ts/.tsx, not this file. */
import { locale, registerCatalog } from './i18n.js';
import { engineFetch, assertEngineResponse, captureEngineSession } from './engine-fetch.js';
const loads = new Map();
/** Catalog paths are relative to plugin.json, never to the entry's web/ directory. */
export async function loadPluginCatalog(manifest) {
    const generation = (loads.get(manifest.id) ?? 0) + 1;
    loads.set(manifest.id, generation);
    registerCatalog(manifest.id);
    if (locale() === 'en' || locale() === 'en-XA')
        return;
    const path = manifest.i18n?.[locale()];
    if (!path || !manifest.base)
        return;
    // Keep credentialed requests within this plugin's directory. Reject encoded
    // separators and traversal as well as absolute URLs and query strings.
    if (!/^[a-zA-Z0-9_./-]+\.json$/.test(path) || path.startsWith('/') || path.split('/').some(p => !p || p === '.' || p === '..'))
        return;
    try {
        const assertCurrent = captureEngineSession();
        const fetcher = manifest.source === 'engine' ? engineFetch : fetch;
        const response = await fetcher(manifest.base + '/' + path, {
            credentials: 'same-origin', cache: 'no-store',
            headers: { 'X-Requested-With': 'OpenIntegrationEngine-WebAdmin' },
            signal: AbortSignal.timeout(2000)
        });
        if (!response.ok)
            return;
        const data = await response.json();
        assertCurrent();
        if (manifest.source === 'engine')
            assertEngineResponse(response);
        if (loads.get(manifest.id) !== generation)
            return;
        registerCatalog(manifest.id, data);
    }
    catch (error) {
        console.warn('[i18n] Plugin catalog unavailable:', manifest.id, error);
    }
}
