/* GENERATED by tools/build-core.mjs from the sibling .ts source — edit the .ts, not this file. */
import { js as jsBeautify } from "js-beautify";
import { post } from "./api.js";
import { webSupportBase } from "./websupport.js";
function flattenProps(props) {
  if (!props || typeof props !== "object") return "";
  const lines = [];
  for (const [k, v] of Object.entries(props)) {
    if (k.startsWith("@")) continue;
    if (v === null || v === void 0) continue;
    if (typeof v === "object") continue;
    lines.push(`${k}=${v}`);
  }
  return lines.join("\n");
}
async function serializeTemplate(dataType, serializationProperties, message) {
  try {
    const base = await webSupportBase();
    if (base === null) return null;
    const text = await post(`${base}/datatypes/_serialize`, String(message ?? ""), {
      contentType: "text/plain",
      params: { dataType, props: flattenProps(serializationProperties) || void 0 },
      raw: true,
      noAuthHandler: true
    });
    const j = JSON.parse(text);
    return { format: j.format, text: j.data, meta: j.meta || null };
  } catch {
    return null;
  }
}
async function validateScript(script) {
  try {
    const base = await webSupportBase();
    if (base === null) return { ok: null, message: "Validation unavailable \u2014 the Web Support plugin is not installed on this engine." };
    const text = await post(`${base}/javascript/_validate`, String(script ?? ""), {
      contentType: "text/plain",
      raw: true,
      noAuthHandler: true
    });
    const err = (JSON.parse(text).error || "").trim();
    return err ? { ok: false, message: err } : { ok: true };
  } catch (e) {
    return { ok: null, message: e?.message || "Validation unavailable." };
  }
}
const PROLOG_RE = /<<\s*\?\s*xml\s+version\s*=\s*"([^"]*)"(?:\s+encoding\s*=\s*"([^"]*)")?\s*\?\s*>/g;
const BEAUTIFY_OPTS = { e4x: true, indent_with_tabs: true };
async function formatScript(script) {
  try {
    const src = String(script ?? "");
    if (!src.trim()) return src;
    const formatted = jsBeautify(src, BEAUTIFY_OPTS);
    return typeof formatted === "string" ? formatted.replace(PROLOG_RE, (_m, version, encoding) => `<?xml version="${version}"${encoding != null ? ` encoding="${encoding}"` : ""}?>`) : null;
  } catch {
    return null;
  }
}
export {
  formatScript,
  serializeTemplate,
  validateScript
};
