/* GENERATED by tools/build-core.mjs from the sibling TypeScript source — edit the .ts/.tsx, not this file. */
/*
 * Locates the web-support endpoints on the connected engine. They exist in two forms:
 *
 *   - engine-native: /api/datatypes/_serialize, /api/javascript/_validate, /api/webplugins
 *     (an engine built with the feat/web-support endpoints)
 *   - the "websupport" plugin: the same endpoints under /api/extensions/websupport/...
 *     (any stock engine with the Web Support extension installed — no engine changes)
 *
 * Probed once per session with the native form preferred, so an engine that some day
 * ships the endpoints wins automatically over the plugin. Returns the path prefix to
 * put after /api ('' for native, '/extensions/websupport' for the plugin), or null when
 * neither exists — callers degrade (no message trees, no server validation, no
 * engine-served plugin UIs) rather than error.
 */
import { get } from './api.js';
let resolved = null;
// Only an unsupported route proves absence. Authentication/authorization,
// network errors and temporary server failures must remain retryable; caching
// them as absence disables plugin UIs, serialization and validation all session.
function missing(e) {
    const status = e && e.status;
    return status === 404 || status === 405;
}
async function probe() {
    try {
        await get('/webplugins', undefined, { noAuthHandler: true });
        return '';
    }
    catch (e) {
        if (!missing(e))
            throw e;
    }
    try {
        await get('/extensions/websupport/webplugins', undefined, { noAuthHandler: true });
        return '/extensions/websupport';
    }
    catch (e) {
        if (!missing(e))
            throw e;
    }
    return null;
}
/** Path prefix for web-support endpoints ('' | '/extensions/websupport'), or null if unavailable. */
export function webSupportBase() {
    if (!resolved) {
        resolved = probe().catch((e) => { resolved = null; throw e; });
    }
    return resolved;
}
