/* GENERATED by tools/build-core.mjs from the sibling .ts source — edit the .ts, not this file. */
import { get } from "./api.js";
let resolved = null;
async function probe() {
  try {
    await get("/webplugins", void 0, { noAuthHandler: true });
    return "";
  } catch (e) {
    if (e && e.status === 401) throw e;
  }
  try {
    await get("/extensions/websupport/webplugins", void 0, { noAuthHandler: true });
    return "/extensions/websupport";
  } catch (e) {
    if (e && e.status === 401) throw e;
  }
  return null;
}
function webSupportBase() {
  if (!resolved) {
    resolved = probe().catch((e) => {
      resolved = null;
      throw e;
    });
  }
  return resolved;
}
export {
  webSupportBase
};
