/* GENERATED by tools/build-core.mjs from the sibling .ts source — edit the .ts, not this file. */
const XSTREAM_SCALARS = /* @__PURE__ */ new Set(["string", "int", "long", "short", "byte", "double", "float", "boolean", "char", "date", "null", "big-decimal", "big-int"]);
const XSTREAM_COLLECTIONS = /* @__PURE__ */ new Set(["list", "linked-list", "array-list", "set", "linked-hash-set", "sorted-set", "tree-set"]);
const XSTREAM_MAPS = /* @__PURE__ */ new Set(["map", "linked-hash-map", "hash-map", "tree-map", "sorted-map", "concurrent-hash-map", "properties"]);
const asList = (v) => v === null || v === void 0 || v === "" ? [] : Array.isArray(v) ? v : [v];
const toArray = (x) => x === void 0 ? [] : Array.isArray(x) ? x : [x];
function collItems(inner) {
  if (inner === "" || inner === null || inner === void 0) return [];
  if (Array.isArray(inner)) return inner;
  if (typeof inner === "object") {
    const node = inner;
    const ks = Object.keys(node).filter((k) => !k.startsWith("@"));
    if (ks.length === 1) {
      const val = node[ks[0]];
      return Array.isArray(val) ? val.map((x) => ({ [ks[0]]: x })) : [{ [ks[0]]: val }];
    }
  }
  return [inner];
}
function formatCustomMap(inner) {
  if (!inner || typeof inner !== "object") return null;
  const node = inner;
  const strings = toArray(node.string);
  const lists = toArray(node.list);
  const ints = toArray(node.int);
  const size = ints.length ? Number(ints[ints.length - 1]) : null;
  let parts;
  if (lists.length && strings.length === lists.length) {
    parts = strings.map((k, i) => `${k}=${toDisplayString({ list: lists[i] })}`);
  } else if (size != null && strings.length === size * 2) {
    parts = [];
    for (let i = 0; i + 1 < strings.length; i += 2) parts.push(`${strings[i]}=${strings[i + 1]}`);
  } else if (strings.length && !lists.length) {
    parts = strings.slice();
  } else {
    return null;
  }
  return "{" + parts.join(", ") + "}";
}
function formatEntryMap(node) {
  if (!node || typeof node !== "object" || node.entry === void 0) return "{}";
  const parts = [];
  for (const entry of asList(node.entry)) {
    if (!entry || typeof entry !== "object") continue;
    const pair = parseMapEntry(entry);
    if (pair) parts.push(`${pair[0]}=${pair[1]}`);
  }
  return "{" + parts.join(", ") + "}";
}
function toDisplayString(v) {
  if (v === null || v === void 0) return "";
  if (typeof v !== "object") return String(v);
  const node = v;
  const cls = node["@class"];
  if (node["@serialization"] === "custom" && typeof cls === "string" && /map/i.test(cls) && node[cls]) {
    const m = formatCustomMap(node[cls]);
    if (m != null) return m;
  }
  const keys = Object.keys(node).filter((k) => !k.startsWith("@"));
  if (!keys.length) return "";
  if (keys.includes("status") && (keys.includes("statusMessage") || keys.includes("message"))) {
    const sm = node.statusMessage;
    return String(node.status ?? "") + (sm ? ": " + String(sm) : "");
  }
  if (keys.length === 1) {
    const type = keys[0];
    const inner = node[type];
    if (type === "entry") return formatEntryMap(node);
    if (XSTREAM_SCALARS.has(type)) return inner == null ? "" : String(inner);
    if (XSTREAM_COLLECTIONS.has(type)) return "[" + collItems(inner).map(toDisplayString).join(", ") + "]";
    if (XSTREAM_MAPS.has(type)) return formatEntryMap(inner);
    if (inner && typeof inner === "object") return toDisplayString(inner);
    return inner == null ? "" : String(inner);
  }
  if (keys.includes("entry")) return formatEntryMap(node);
  try {
    return JSON.stringify(v) ?? String(v);
  } catch {
    return String(v);
  }
}
function mapNode(mc) {
  let cur = mc && typeof mc === "object" && mc.content !== void 0 ? mc.content : mc;
  for (let i = 0; i < 5 && cur && typeof cur === "object" && cur.entry === void 0; i++) {
    const keys = Object.keys(cur).filter((k) => !k.startsWith("@"));
    if (keys.length !== 1) break;
    cur = cur[keys[0]];
  }
  return cur;
}
function parseMapEntry(entry) {
  const pairs = Object.entries(entry).filter(([k]) => !k.startsWith("@"));
  if (!pairs.length) return null;
  if (pairs.length === 1 && pairs[0][0] === "string" && Array.isArray(pairs[0][1])) {
    return [String(pairs[0][1][0] ?? ""), toDisplayString(pairs[0][1][1])];
  }
  const k0 = pairs[0];
  const key = k0[1] && typeof k0[1] === "object" ? toDisplayString({ [k0[0]]: k0[1] }) : String(k0[1] ?? "");
  const value = pairs.length >= 2 ? toDisplayString({ [pairs[1][0]]: pairs[1][1] }) : "";
  return [key, value];
}
function mappingEntries(mc) {
  const node = mapNode(mc);
  if (!node || typeof node !== "object" || node.entry === void 0) return [];
  const out = [];
  for (const entry of asList(node.entry)) {
    if (!entry || typeof entry !== "object") continue;
    const pair = parseMapEntry(entry);
    if (pair) out.push(pair);
  }
  return out;
}
function directChildText(root, tag) {
  for (const node of root.childNodes) {
    if (node.nodeType === 1 && node.nodeName === tag) return node.textContent || "";
  }
  return "";
}
function parseResponse(content) {
  if (typeof content !== "string" || !/^\s*</.test(content)) return null;
  try {
    const doc = new DOMParser().parseFromString(content, "text/xml");
    const root = doc.documentElement;
    if (!root || doc.querySelector("parsererror") || root.nodeName !== "response") return null;
    return {
      status: directChildText(root, "status"),
      statusMessage: directChildText(root, "statusMessage"),
      message: directChildText(root, "message")
    };
  } catch {
    return null;
  }
}
export {
  mapNode,
  mappingEntries,
  parseResponse,
  toDisplayString
};
