/*
 * Builds the TypeScript core modules: client/core/*.ts -> *.js, the raw-served
 * framework files the app bundle and runtime plugins import by stable URL
 * (/core/api.js, /core/pkg-api.js, ...). Like tools/build-connectors.mjs but
 * for core: transpile-only (bundle:false), so every import specifier is kept
 * as-is and resolves at runtime through the page importmap / served paths —
 * one shared framework instance. Type-only imports (`import type`) are erased,
 * so pure type modules (wire-types, oie-schema.d.ts) never become runtime
 * requests.
 *
 * Both the .ts source and the generated .js are checked in (same model as the
 * connector .jsx -> .js pairs): edit the .ts, then rerun this (or `npm run
 * build`; `npm run dev`/`npm start` also regenerate on boot). A core module
 * with no .ts source is plain JavaScript and is left as-is.
 */
import { build } from 'esbuild';
import { readdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const coreDir = path.join(root, 'client', 'core');

const entryPoints = {};
for (const name of readdirSync(coreDir)) {
    if (!name.endsWith('.ts') || name.endsWith('.d.ts')) continue;
    entryPoints[`client/core/${name.slice(0, -3)}`] = path.join(coreDir, name);
}

const names = Object.keys(entryPoints);
if (!names.length) { console.log('[build-core] no TypeScript core modules'); process.exit(0); }

await build({
    entryPoints,
    outdir: root,
    bundle: false,           // transpile only — keep every import for raw-serving
    format: 'esm',
    target: 'es2022',
    banner: { js: '/* GENERATED by tools/build-core.mjs from the sibling .ts source — edit the .ts, not this file. */' },
    logLevel: 'warning',
});
console.log(`[build-core] built ${names.length} core module(s): ${names.map(n => n.split('/').pop()).join(', ')}`);
